var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(a,b){if(b){var c=ba;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
k("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});k("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var f=d.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});
k("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});function ca(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function da(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:ca(a)}}
k("Promise",function(a){function b(e){this.c=0;this.i=void 0;this.a=[];var g=this.f();try{e(g.resolve,g.reject)}catch(l){g.reject(l)}}function c(){this.a=null}function d(e){return e instanceof b?e:new b(function(g){g(e)})}if(a)return a;c.prototype.c=function(e){if(null==this.a){this.a=[];var g=this;this.f(function(){g.i()})}this.a.push(e)};var f=ba.setTimeout;c.prototype.f=function(e){f(e,0)};c.prototype.i=function(){for(;this.a&&this.a.length;){var e=this.a;this.a=[];for(var g=0;g<e.length;++g){var l=
e[g];e[g]=null;try{l()}catch(m){this.h(m)}}}this.a=null};c.prototype.h=function(e){this.f(function(){throw e;})};b.prototype.f=function(){function e(m){return function(q){l||(l=!0,m.call(g,q))}}var g=this,l=!1;return{resolve:e(this.w),reject:e(this.h)}};b.prototype.w=function(e){if(e===this)this.h(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof b)this.A(e);else{a:switch(typeof e){case "object":var g=null!=e;break a;case "function":g=!0;break a;default:g=!1}g?this.v(e):this.m(e)}};
b.prototype.v=function(e){var g=void 0;try{g=e.then}catch(l){this.h(l);return}"function"==typeof g?this.B(g,e):this.m(e)};b.prototype.h=function(e){this.o(2,e)};b.prototype.m=function(e){this.o(1,e)};b.prototype.o=function(e,g){if(0!=this.c)throw Error("Cannot settle("+e+", "+g+"): Promise already settled in state"+this.c);this.c=e;this.i=g;this.u()};b.prototype.u=function(){if(null!=this.a){for(var e=0;e<this.a.length;++e)h.c(this.a[e]);this.a=null}};var h=new c;b.prototype.A=function(e){var g=this.f();
e.l(g.resolve,g.reject)};b.prototype.B=function(e,g){var l=this.f();try{e.call(g,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(e,g){function l(t,w){return"function"==typeof t?function(W){try{m(t(W))}catch(X){q(X)}}:w}var m,q,u=new b(function(t,w){m=t;q=w});this.l(l(e,m),l(g,q));return u};b.prototype.catch=function(e){return this.then(void 0,e)};b.prototype.l=function(e,g){function l(){switch(m.c){case 1:e(m.i);break;case 2:g(m.i);break;default:throw Error("Unexpected state: "+
m.c);}}var m=this;null==this.a?h.c(l):this.a.push(l)};b.resolve=d;b.reject=function(e){return new b(function(g,l){l(e)})};b.race=function(e){return new b(function(g,l){for(var m=da(e),q=m.next();!q.done;q=m.next())d(q.value).l(g,l)})};b.all=function(e){var g=da(e),l=g.next();return l.done?d([]):new b(function(m,q){function u(W){return function(X){t[W]=X;w--;0==w&&m(t)}}var t=[],w=0;do t.push(void 0),w++,d(l.value).l(u(t.length-1),q),l=g.next();while(!l.done)})};return b});
var n=["verse","group","search","favorites"],ea=n.indexOf("verse"),fa=n.indexOf("group"),ha=n.indexOf("search"),ia=n.indexOf("favorites"),p=document.getElementById("verseDisplay"),r=document.getElementById("partSelect"),v=document.getElementById("verseSelect"),x=document.getElementById("verseGroupSelect"),y=document.getElementById("verseNavTop"),z=document.getElementById("verseNavBottom"),ja=y.cloneNode(!0),A=document.getElementById("bookmarkDisplay"),B=document.getElementById("favoritesDisplay"),
ka=document.querySelector(".verse-options"),C=document.getElementById("searchTxt"),la=document.getElementById("searchBtn"),ma=document.getElementById("searchClearBtn"),D=document.getElementById("searchResults"),E=document.getElementById("groupView"),na=document.getElementById("hideButtonLabelCbx"),F={view:0,selectedPart:1,selectedVerse:1,selectedVerseGroup:"1:1-20",searchStr:"",hideButtonLabel:!1,verseOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1},
groupOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!1,showEnglish2:!1},searchOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1},favoritesOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1},isDataLoaded:!1},G={favorites:[],bookmark:0},H=null,I=null;
function oa(){var a=document.querySelector(".modal-window");a&&(a.onclick=function(){window.location="#"});r.onchange=function(){J(parseInt(r.value,10));K(1);L()};v.onchange=function(){K(parseInt(v.value,10));L()};x.onchange=function(){M(x.value);N()};M(F.selectedVerseGroup);J(F.selectedPart);K(F.selectedVerse);O(F.view);C.onkeyup=function(b){13===b.keyCode&&pa()};C.value=F.searchStr;la.onclick=function(){pa()};ma.onclick=function(){C.value="";C.focus()};qa()}
function qa(){var a=document.querySelector(".of-bottom-menu");F.hideButtonLabel&&ra(a,"of-hide-labels");na.checked=F.hideButtonLabel;na.onclick=function(){var b=F.hideButtonLabel;"undefined"===b&&(b=!1);F.hideButtonLabel=!b;na.checked=!b;b?sa(a,"of-hide-labels"):ra(a,"of-hide-labels");P()}}function pa(){F.searchStr=C.value.trim();ta()}function Q(){F.view===ea?L():F.view===fa?N():F.view===ha?ta():F.view===ia&&ua()}function J(a){F.selectedPart=a;r.value=F.selectedPart;va(a)}
function K(a){F.selectedVerse=a;v.value=F.selectedVerse}function M(a){F.selectedVerseGroup=a;x.value=F.selectedVerseGroup}function wa(a){var b=H.verses.length;return 0>=a?H.verses[b-1]:a>b?H.verses[0]:H.verses[a-1]}function R(a,b){for(var c=H.verses.length,d=0;d<c;d++){var f=H.verses[d];if(f.part===a&&f.verse===b)return f}return null}
function O(a){F.view=a;n.map(function(d){var f=document.getElementById(d+"View");f&&(f.style.display="none");f=document.querySelectorAll("."+d+"-view");for(var h=0;h<f.length;h++)f[h].style.display="none";(f=document.getElementById(d+"ViewMenuItem"))||console.log(d+"ViewMenuItem not found.");sa(f,"selected")});a=n[a];var b=document.getElementById(a+"View"),c=document.querySelectorAll("."+a+"-view");b.style.display="";b.classList.add("animated","fadeIn");b.addEventListener("animationend",function(){});
for(b=0;b<c.length;b++)c[b].style.display="";ra(document.querySelector("#"+a+"ViewMenuItem"),"selected");P();Q()}function L(){var a=F.selectedPart,b=F.selectedVerse;(I=R(a,b))?(xa(),p.innerHTML=S(I,"verse",null),T(p,I)):p.innerHTML="Verse "+a+":"+b+" not found!"}
function T(a,b){if(a&&b){var c=a.querySelector(".verse-btn"),d=a.querySelector(".read-btn"),f=a.querySelector(".favorite-btn"),h=a.querySelector(".bookmark-btn"),e=b.part,g=b.verse,l=e+":"+g;c&&(c.onclick=function(){J(e);K(g);O(ea)});if(d){var m=ya(e,g);d.onclick=function(){M(m);O(fa);window.location.hash="verse"+e+"-"+g}}G.favorites.includes(l)?(f.classList.add("favorited"),f.title="Remove from Favorites"):f.title="Add to Favorites";l===G.bookmark?(h.classList.add("favorited"),h.title="Remove Bookmark"):
h.title="Bookmark";f.addEventListener("animationend",function(){f.classList.remove("animated","pulse","tada");Q()});h.addEventListener("animationend",function(){h.classList.remove("animated","pulse","tada");Q()});f.onclick=function(){G.favorites.includes(l)?(G.favorites.splice(G.favorites.indexOf(l),1),f.classList.remove("favorited"),f.classList.add("animated","pulse")):(G.favorites.push(l),G.favorites.sort(za),f.classList.add("favorited","animated","tada"));Aa()};h.onclick=function(){G.bookmark===
l?(G.bookmark=!1,h.classList.remove("favorited"),h.classList.add("animated","pulse")):G.bookmark!==l&&(G.bookmark=l,h.classList.add("favorited","animated","tada"));Aa()}}}function U(a){return a&&-1<a.indexOf(":")?(a=a.split(":"),{b:parseInt(a[0],10),g:parseInt(a[1],10)}):null}function za(a,b){a=U(a);var c=U(b);return a.b<c.b?-1:a.b>c.b?1:a.g<b.g?-1:a.g>c.g?1:0}
function ya(a,b){if(a&&b){var c=H.verseGroups[a-1].groups;if(c)for(var d=0;d<c.length;d++){var f=c[d],h=f.split("-"),e=parseInt(h[1],10);if(b>=parseInt(h[0],10)&&b<=e)return a+":"+f}console.log("ERROR: getVerseGroupByPartVerse parameters ("+a+", "+b+") not found.");return null}console.log("ERROR: getVerseGroupByPartVerse parameters (part, verse) are not valid.")}
function N(){y.style.display="";z.style.display="";var a;if(a=F.selectedVerseGroup){a=a.split(":");var b=a[1],c=b.split("-");a={b:parseInt(a[0],10),C:parseInt(c[0],10),s:parseInt(c[1],10),D:b}}else a=null;if(a){E.innerHTML="";for(b=a.C;b<=a.s;b++){c=R(a.b,b);var d=document.createElement("div");d.innerHTML=S(c,"group",null);T(d,c);E.appendChild(d)}b=a.b;var f="",h="";c=H.verseGroups[b-1];d=c.groups.length;for(var e=0;e<d;e++)a.D===c.groups[e]&&(0<e?f=b+":"+c.groups[e-1]:1===b?(f=H.verseGroups[16].groups,
f="17:"+f[f.length-1]):(f=b-1,h=H.verseGroups[f-1].groups,f=f+":"+h[h.length-1]),h=e<d-1?b+":"+c.groups[e+1]:17===b?"1:"+H.verseGroups[0].groups[0]:b+1+":"+H.verseGroups[b].groups[0]);Ba(f,h)}}
function ua(){y.style.display="none";z.style.display="none";var a=G.bookmark,b=G.favorites;if(a){var c=U(G.bookmark);A.innerHTML="<h3>Bookmark</h3>"+S(R(c.b,c.g),"favorites","");T(A,c)}else A.innerHTML="";b&&0<b.length?(B.innerHTML='<h3 style="border-bottom: 1px solid gray;">Favorites</h3>',b.map(function(d){d=U(d);var f=document.createElement("div");f.innerHTML=S(R(d.b,d.g),"favorites","");T(f,d);B.appendChild(f)})):B.innerHTML="";a||b&&0!==b.length||(B.innerHTML="Bookmark and favorites have not been set.")}
function ta(){y.style.display="none";z.style.display="none";var a=F.searchStr;if(a){var b=0,c=[],d=H.verses.length;D.innerHTML="";for(var f=0;f<d;f++){var h=H.verses[f],e=new RegExp(a,"i"),g=document.createElement("div"),l=[];F.searchOptions.showRomanized&&l.push(h.ro);F.searchOptions.showJapanese&&l.push(h.jp1+h.jp2);F.searchOptions.showEnglish&&l.push(h.en_6th_ed);F.searchOptions.showPortuguese&&l.push(h.pt);F.searchOptions.showKanji&&l.push(h.kanji);l.join(" ").match(e)&&(b++,g.innerHTML=S(h,"search",
a),T(g,h),c.push(g))}d=document.createElement("div");d.innerHTML='<p>Search "'+a+'" yields '+b+" results.</p>";D.appendChild(d);for(a=0;a<c.length;a++)D.appendChild(c[a])}else D.innerHTML="<p>Enter a search term.</p>";C.select()}function Ca(){var a=[];H.verseGroups.map(function(b){var c=b.part;a.push('<option value="" disabled="true">- Part '+c+" -</option>");b.groups.map(function(d){d=c+":"+d;a.push('<option value="'+d+'">'+d+"</option>")})});x.innerHTML=a.join("")}
function Ba(a,b){function c(){E.classList.add("animated","slideOutLeft");E.addEventListener("animationend",function(){M(b);N();E.className="";E.classList.add("animated","slideInRight");E.addEventListener("animationend",function(){E.className=""})})}function d(){E.classList.add("animated","slideOutRight");E.addEventListener("animationend",function(){M(a);N();E.className="";E.classList.add("animated","slideInLeft");E.addEventListener("animationend",function(){E.className=""})})}V(y,F.selectedVerseGroup,
d,c);V(z,F.selectedVerseGroup,d,c)}function xa(){function a(){J(f.part);K(f.verse);L()}function b(){J(d.part);K(d.verse);L()}var c="Verse "+I.part+":"+I.verse,d=wa(I.id-1),f=wa(I.id+1);V(y,c,b,a);V(z,c,b,a)}function V(a,b,c,d){a.innerHTML=ja.innerHTML;var f=a.getElementsByClassName("verse-nav-next-btn")[0],h=a.getElementsByClassName("verse-nav-middle")[0];a.getElementsByClassName("verse-nav-prev-btn")[0].onclick=c;f.onclick=d;h.innerHTML=b}
function S(a,b,c){c=c||!1;if(a){var d=a.part+":"+a.verse,f=Y(a.ro.split(/\s{2,}/g).join("<br/>"),c),h=Y(a.kanji.split(/\s{2,}/g).join("<br/>"),c),e=Y(a.en_6th_ed,c),g=Y(a.pt,c);c=Y(a.jp1+"<br/>"+a.jp2,c);return'<div class="verse-display">'+(F[b+"Options"].showRomanized?"<blockquote>"+f+"</blockquote>":"")+(F[b+"Options"].showJapanese?"<blockquote>"+c+"</blockquote>":"")+(F[b+"Options"].showEnglish?"<blockquote>"+e+"</blockquote>":"")+(F[b+"Options"].showPortuguese?"<blockquote>"+g+"</blockquote>":
"")+(F[b+"Options"].showKanji?"<blockquote>"+h+"</blockquote>":"")+'<table class="of-verse-controls"><tbody><tr><td><button class="favorite-btn btn circle"><i class="fa fa-fw fa-star"></i></button><button class="bookmark-btn btn circle"><i class="fa fa-fw fa-bookmark"></i></button></td><td>'+(a.in_life_of_oyasama?'<span class="of-tag">Life of Oyasama</span>':"")+(a.in_doctrine?'<span class="of-tag">Doctrine</span>':"")+"</td><td>"+d+"</td><td>"+("group"!==b?'<button class="read-btn btn circle" title="View in Read"><i class="fab fa-fw fa-readme"></i></button>':
"")+("verse"!==b?'<button class="verse-btn btn circle" title="View in Browse"><i class="fa fa-fw fa-eye"></i></button>':"")+"</td></tr></tbody></table></div>"}return"Verse not found."}function Y(a,b){if(!b)return a;b=new RegExp(b,"i");var c='<span class="highlight">'+a.match(b)+"</span>";return a.replace(b,c)}
function Da(){n.map(function(a){for(var b=ka.cloneNode(!0),c=b.querySelectorAll("input"),d=b.querySelectorAll("label"),f={},h=0;h<c.length;f={j:f.j},h++){var e=c[h],g=e.id.replace("-verse","-"+a);f.j=e.id.replace("-verse","").replace("show","").replace("Cbx","");e.id=g;e.onchange=function(l){return function(){var m=l.j,q=document.getElementById("show"+m+"Cbx-"+a);if(q){var u=F[a+"Options"]["show"+m];"undefined"===u&&(u=!1);F[a+"Options"]["show"+m]=!u;q.checked=!u}Q()}}(f);e.checked=F[a+"Options"]["show"+
f.j]}for(c=0;c<d.length;c++)d[c].htmlFor=d[c].htmlFor.replace("-verse","-"+a);d=document.getElementById(a+"OptionsRow");d.innerHTML="";d.appendChild(b);document.getElementById(a+"ViewMenuItem").onclick=function(){O(n.indexOf(a))}})}function va(a){var b=[];H.verses.map(function(c){c.part===parseInt(a,10)&&(c=c.verse,b.push('<option value="'+c+'"'+(F.selectedVerse===c?' selected="selected"':"")+">"+c+"</option>"))});v.innerHTML=b.join("");v.value=F.selectedVerse}
window.onload=function(){Ea().then(function(){return Fa("ofudesaki.json")}).then(function(a){H=JSON.parse(a.responseText);return Fa("keywords.json")}).then(function(a){JSON.parse(a.responseText);P();a=[];for(var b=1;18>=b;b++)a.push('<option value="'+b+'">'+b+"</option>");r.innerHTML=a.join("");va(F.selectedPart);Ca();oa();Da();F.isDataLoaded=!0}).catch(function(a){console.log("Something went wrong.",a)})};window.onunload=function(){F.isDataLoaded&&(P(),Aa())};
function Ea(){return new Promise(function(a,b){var c=window.localStorage.getItem("ofudesaki-browser"),d=window.localStorage.getItem("ofudesaki-browser-favorites");c&&((c=JSON.parse(c))?(F=c,F.favoritesOptions||(F.favoritesOptions={showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1})):b(Error("Failed to load data from local storage.")));d&&((d=JSON.parse(d))?G=d:b(Error("Failed to load fav data from local storage.")));a("Data loaded from local storage.")})}
function P(){window.localStorage.setItem("ofudesaki-browser",JSON.stringify(F))}function Aa(){window.localStorage.setItem("ofudesaki-browser-favorites",JSON.stringify(G))}function Fa(a){var b=void 0===b?"GET":b;var c=new XMLHttpRequest;return new Promise(function(d,f){c.onreadystatechange=function(){4===c.readyState&&(200<=c.status&&300>c.status?d(c):f({status:c.status,statusText:c.statusText}))};c.open(b||"GET",a,!0);c.send()})}
function Z(a){for(var b=a.className.split(/\s+/),c=b.length,d=0;d<c;d++)if("active"===b[d]){b.splice(d,1);break}c===b.length&&b.push("active");a.className=b.join(" ")}function sa(a,b){for(var c=a.className.split(/\s+/),d=c.length,f=0;f<d;f++)if(c[f]===b){c.splice(f,1);break}a.className=c.join(" ")}function ra(a,b){var c=a.className.split(/\s+/);c.push(b);a.className=c.join(" ")}
(function(a,b){var c=b.getElementById("layout"),d=b.getElementById("menu"),f=b.getElementById("menuLink");a=b.getElementById("main");f.onclick=function(h){h.preventDefault();Z(c);Z(d);Z(f)};a.onclick=function(h){-1!==d.className.indexOf("active")&&(h.preventDefault(),Z(c),Z(d),Z(f))}})(window,window.document);
