var f="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},h="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(a,b){if(b){var c=h;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&f(c,a,{configurable:!0,writable:!0,value:b})}}
k("Object.is",function(a){return a?a:function(b,a){return b===a?0!==b||1/b===1/a:b!==b&&a!==a}});k("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=b[c];if(g===a||Object.is(g,a))return!0}return!1}});
k("String.prototype.includes",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(a,c||0)}});
var l=document.getElementById("wordView"),m=document.getElementById("roWordView"),n=document.getElementById("keyword"),p=document.getElementById("verseList"),q=document.getElementById("verseDisplay"),t=document.getElementById("englishViewBtn"),u=document.getElementById("englishCountViewBtn"),v=document.getElementById("romanizedViewBtn"),w=document.getElementById("romanizedCountViewBtn"),x={},y={},z=null,A={selectedView:"word",selectedWordStr:"",selectedPartVerse:"",wordSortBy:"A-Z",selectedRoWordStr:"",
selectedRoPartVerse:"",roWordSortBy:"A-Z"};window.onload=function(){B();C()};function C(){t.onclick=function(){A.selectedView="word";A.wordSortBy="A-Z";D()};u.onclick=function(){A.selectedView="word";A.wordSortBy="count";D()};v.onclick=function(){A.selectedView="roWord";A.roWordSortBy="A-Z";D()};w.onclick=function(){A.selectedView="roWord";A.roWordSortBy="count";D()}}
function E(a,b){z.verses.map(function(c){var d=c.part+":"+c.verse;c=c[a].replace(/[^\w\s']/g,"").toLowerCase().split(/\s+/g);for(var e=c.length,g=0;g<e;g++)g<e-2&&c.push(c[g]+" "+c[g+1]);c.map(function(a){a&&(b[a]?(b[a].count++,a=b[a].verses,a.includes(d)||a.push(d)):b[a]={count:1,verses:[d]})})});Object.keys(b).map(function(a){1===b[a].count&&delete b[a]})}function D(){l.style.display="none";m.style.display="none";"word"===A.selectedView?F("word",x):"roWord"===A.selectedView&&F("roWord",y)}
function F(a,b){var c=document.getElementById(a+"View"),d=A[a+"SortBy"],e=Object.keys(b),g=[];c.style.display="block";c.innerHTML="";("count"===d?e.sort(function(a,c){return b[c].count-b[a].count}):e.sort()).map(function(a){g.push("<a href='#verse' class='word'>"+a+" ("+b[a].count+")</a>")});c.innerHTML=g.length+" "+("word"===a?"English":"Romanized")+" words and word-pairs found (Sorted by "+d+").<br/>"+g.join("");a=c.querySelectorAll(".word");c=a.length;d={};for(e=0;e<c;d={a:d.a},e++)d.a=a[e],d.a.onclick=
function(a){return function(){var c=a.a.innerHTML;G(c.substr(0,c.lastIndexOf(" ")),b)}}(d)}
function G(a,b){console.log(a);if(a){A.selectedWordStr=a;var c=b[a].count;n.innerHTML="<strong>Keyword:</strong> "+a;p.innerHTML="<strong>Found in "+c+" verses:</strong> <a href='#verse' class='verse-link'>"+b[a].verses.join("</a>, <a href='#verse' class='verse-link'>")+"</a>";b=p.querySelectorAll(".verse-link");c=b.length;for(var d={},e=0;e<c;d={b:d.b},e++){var g=b[e];d.b=g.innerHTML;g.onclick=function(b){return function(){H(b.b,a)}}(d)}H(b[0].innerHTML,a)}}
function H(a,b){A.selectedPartVerse=a;a:{if(a){var c=a.split(":");var d=parseInt(c[0],10);c=parseInt(c[1],10);for(var e=z.verses.length,g=0;g<e;g++){var r=z.verses[g];if(d===r.part&&c===r.verse){d=r;break a}}}d=null}d&&(c=I(d.ro.split(/\s{2,}/g).join("<br/>"),b),e=d.jp1+"<br/>"+d.jp2,b=I(d.en_6th_ed,b),q.innerHTML="<blockquote>"+c+"</blockquote><blockquote>"+e+"</blockquote><blockquote>"+b+"</blockquote><blockquote>"+d.kanji.split(/\s{2,}/g).join("<br/>")+"</blockquote>In Life of Oyasama?: "+(d.in_life_of_oyasama?
"&#9989;":"&#10060;")+"In Doctrine?: "+(d.in_doctrine?"&#9989;":"&#10060;")+"<span style='float: right;'>"+a+"</span>")}function I(a,b){if(!b)return a;b=new RegExp(b,"i");var c='<span class="highlight">'+a.match(b)+"</span>";return a.replace(b,c)}
function B(){fetch("ofudesaki.json").then(function(a){return a.json()}).then(function(a){(z=a)?((a=window.localStorage.getItem("ofudesaki-analysis"))&&(a=JSON.parse(a))&&(A=a),E("en_6th_ed",x),E("ro",y),G(A.selectedWordStr,x),H(A.selectedPartVerse,A.selectedWordStr),G(A.selectedRoWordStr,y),H(A.selectedRoPartVerse,A.selectedRoWordStr),D()):alert("data not loaded")})}window.addEventListener("unload",function(){window.localStorage.setItem("ofudesaki-analysis",JSON.stringify(A))});
function J(a){for(var b=a.className.split(/\s+/),c=b.length,d=0;d<c;d++)if("active"===b[d]){b.splice(d,1);break}c===b.length&&b.push("active");a.className=b.join(" ")}(function(a,b){var c=b.getElementById("layout"),d=b.getElementById("menu"),e=b.getElementById("menuLink");a=b.getElementById("main");e.onclick=function(a){a.preventDefault();J(c);J(d);J(e)};a.onclick=function(a){-1!==d.className.indexOf("active")&&(a.preventDefault(),J(c),J(d),J(e))}})(window,window.document);
