const f=document.getElementById("wordView"),k=document.getElementById("roWordView"),l=document.getElementById("keyword"),m=document.getElementById("verseList"),p=document.getElementById("verseDisplay"),q=document.getElementById("englishViewBtn"),r=document.getElementById("englishCountViewBtn"),t=document.getElementById("romanizedViewBtn"),u=document.getElementById("romanizedCountViewBtn");
let v={},w={},x=null,y={selectedView:"word",selectedWordStr:"",selectedPartVerse:"",wordSortBy:"count",selectedRoWordStr:"",selectedRoPartVerse:"",roWordSortBy:"count",isDataLoaded:!1};window.onload=function(){z();A()};
function A(){q.onclick=function(){y.selectedView="word";y.wordSortBy="A-Z";B()};r.onclick=function(){y.selectedView="word";y.wordSortBy="count";B()};t.onclick=function(){y.selectedView="roWord";y.roWordSortBy="A-Z";B()};u.onclick=function(){y.selectedView="roWord";y.roWordSortBy="count";B()}}
function C(b,a){x.verses.map(c=>{const d=c.part+":"+c.verse;c=c[b].replace(/[^\w\s']/g,"").toLowerCase().split(/\s+/g);const g=c.length;for(let e=0;e<g;e++)e<g-2&&c.push(c[e]+" "+c[e+1]);c.map(e=>{e&&(a[e]?(a[e].count++,e=a[e].verses,e.includes(d)||e.push(d)):a[e]={count:1,verses:[d]})})});Object.keys(a).map(c=>{1===a[c].count&&delete a[c]})}function B(){f.style.display="none";k.style.display="none";"word"===y.selectedView?D("word",v):"roWord"===y.selectedView&&D("roWord",w)}
function D(b,a){var c=document.getElementById(b+"View"),d=y[b+"SortBy"];const g=Object.keys(a),e=[];c.style.display="block";c.innerHTML="";("count"===d?g.sort(function(h,n){return a[n].count-a[h].count}):g.sort()).map(h=>{e.push("<a href='#verse' class='word'>"+h+" ("+a[h].count+")</a>")});c.innerHTML=e.length+" "+("word"===b?"English":"Romanized")+" words and word-pairs found (Sorted by "+d+").<br/>"+e.join("");b=c.querySelectorAll(".word");c=b.length;for(d=0;d<c;d++){const h=b[d];h.onclick=function(){const n=
h.innerHTML;E(n.substr(0,n.lastIndexOf(" ")),a)}}}function E(b,a){console.log(b);if(b){y.selectedWordStr=b;var c=a[b].count;l.innerHTML="<strong>Keyword:</strong> "+b;m.innerHTML="<strong>Found in "+c+" verses:</strong> <a href='#verse' class='verse-link'>"+a[b].verses.join("</a>, <a href='#verse' class='verse-link'>")+"</a>";a=m.querySelectorAll(".verse-link");c=a.length;for(let d=0;d<c;d++){const g=a[d],e=g.innerHTML;g.onclick=function(){F(e,b)}}F(a[0].innerHTML,b)}}
function F(b,a){y.selectedPartVerse=b;a:{if(b){var c=b.split(":");var d=parseInt(c[0],10);c=parseInt(c[1],10);var g=x.verses.length;for(let e=0;e<g;e++){const h=x.verses[e];if(d===h.part&&c===h.verse){d=h;break a}}}d=null}d&&(c=G(d.ro.split(/\s{2,}/g).join("<br/>"),a),g=d.jp1+"<br/>"+d.jp2,a=G(d.en_6th_ed,a),p.innerHTML="<blockquote>"+c+"</blockquote><blockquote>"+g+"</blockquote><blockquote>"+a+"</blockquote><blockquote>"+d.kanji.split(/\s{2,}/g).join("<br/>")+"</blockquote>In Life of Oyasama?: "+
(d.in_life_of_oyasama?"&#9989;":"&#10060;")+"In Doctrine?: "+(d.in_doctrine?"&#9989;":"&#10060;")+"<span style='float: right;'>"+b+"</span>")}function G(b,a){if(!a)return b;a=new RegExp(a,"i");const c='<span class="highlight">'+b.match(a)+"</span>";return b.replace(a,c)}
function z(){fetch("ofudesaki.json").then(b=>b.json()).then(b=>{(x=b)?((b=window.localStorage.getItem("ofudesaki-analysis"))&&(b=JSON.parse(b))&&(y=b),C("en_6th_ed",v),C("ro",w),E(y.selectedWordStr,v),F(y.selectedPartVerse,y.selectedWordStr),E(y.selectedRoWordStr,w),F(y.selectedRoPartVerse,y.selectedRoWordStr),y.isDataLoaded=!0,B()):alert("data not loaded")})}window.onunload=function(){y.isDataLoaded&&window.localStorage.setItem("ofudesaki-analysis",JSON.stringify(y))};
function H(b){let a=b.className.split(/\s+/),c=a.length;for(let d=0;d<c;d++)if("active"===a[d]){a.splice(d,1);break}c===a.length&&a.push("active");b.className=a.join(" ")}(function(b,a){var c=a.getElementById("layout"),d=a.getElementById("menu"),g=a.getElementById("menuLink");b=a.getElementById("main");g.onclick=function(e){e.preventDefault();H(c);H(d);H(g)};b.onclick=function(e){-1!==d.className.indexOf("active")&&(e.preventDefault(),H(c),H(d),H(g))}})(window,window.document);
