var g="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function k(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var l=k(this);
function m(a,b){if(b){var c=l;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&g(c,a,{configurable:!0,writable:!0,value:b})}}m("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
m("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
m("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});
var p=document.getElementById("wordView"),q=document.getElementById("roWordView"),r=document.getElementById("keyword"),t=document.getElementById("verseList"),u=document.getElementById("verseDisplay"),v=document.getElementById("englishViewBtn"),w=document.getElementById("englishCountViewBtn"),x=document.getElementById("romanizedViewBtn"),y=document.getElementById("romanizedCountViewBtn"),z={},A={},B=null,C={selectedView:"word",selectedWordStr:"",selectedPartVerse:"",wordSortBy:"count",selectedRoWordStr:"",
selectedRoPartVerse:"",roWordSortBy:"count",isDataLoaded:!1};window.onload=function(){D();E()};function E(){v.onclick=function(){C.selectedView="word";C.wordSortBy="A-Z";F()};w.onclick=function(){C.selectedView="word";C.wordSortBy="count";F()};x.onclick=function(){C.selectedView="roWord";C.roWordSortBy="A-Z";F()};y.onclick=function(){C.selectedView="roWord";C.roWordSortBy="count";F()}}
function G(a,b){B.verses.map(function(c){var d=c.part+":"+c.verse;c=c[a].replace(/[^\w\s']/g,"").toLowerCase().split(/\s+/g);for(var e=c.length,f=0;f<e;f++)f<e-2&&c.push(c[f]+" "+c[f+1]);c.map(function(h){h&&(b[h]?(b[h].count++,h=b[h].verses,h.includes(d)||h.push(d)):b[h]={count:1,verses:[d]})})});Object.keys(b).map(function(c){1===b[c].count&&delete b[c]})}function F(){p.style.display="none";q.style.display="none";"word"===C.selectedView?H("word",z):"roWord"===C.selectedView&&H("roWord",A)}
function H(a,b){var c=document.getElementById(a+"View"),d=C[a+"SortBy"],e=Object.keys(b),f=[];c.style.display="block";c.innerHTML="";("count"===d?e.sort(function(h,n){return b[n].count-b[h].count}):e.sort()).map(function(h){f.push("<a href='#verse' class='word'>"+h+" ("+b[h].count+")</a>")});c.innerHTML=f.length+" "+("word"===a?"English":"Romanized")+" words and word-pairs found (Sorted by "+d+").<br/>"+f.join("");a=c.querySelectorAll(".word");c=a.length;d={};for(e=0;e<c;d={a:d.a},e++)d.a=a[e],d.a.onclick=
function(h){return function(){var n=h.a.innerHTML;I(n.substr(0,n.lastIndexOf(" ")),b)}}(d)}
function I(a,b){console.log(a);if(a){C.selectedWordStr=a;var c=b[a].count;r.innerHTML="<strong>Keyword:</strong> "+a;t.innerHTML="<strong>Found in "+c+" verses:</strong> <a href='#verse' class='verse-link'>"+b[a].verses.join("</a>, <a href='#verse' class='verse-link'>")+"</a>";b=t.querySelectorAll(".verse-link");c=b.length;for(var d={},e=0;e<c;d={b:d.b},e++){var f=b[e];d.b=f.innerHTML;f.onclick=function(h){return function(){J(h.b,a)}}(d)}J(b[0].innerHTML,a)}}
function J(a,b){C.selectedPartVerse=a;a:{if(a){var c=a.split(":");var d=parseInt(c[0],10);c=parseInt(c[1],10);for(var e=B.verses.length,f=0;f<e;f++){var h=B.verses[f];if(d===h.part&&c===h.verse){d=h;break a}}}d=null}d&&(c=K(d.ro.split(/\s{2,}/g).join("<br/>"),b),e=d.jp1+"<br/>"+d.jp2,b=K(d.en_6th_ed,b),u.innerHTML="<blockquote>"+c+"</blockquote><blockquote>"+e+"</blockquote><blockquote>"+b+"</blockquote><blockquote>"+d.kanji.split(/\s{2,}/g).join("<br/>")+"</blockquote>In Life of Oyasama?: "+(d.in_life_of_oyasama?
"&#9989;":"&#10060;")+"In Doctrine?: "+(d.in_doctrine?"&#9989;":"&#10060;")+"<span style='float: right;'>"+a+"</span>")}function K(a,b){if(!b)return a;b=new RegExp(b,"i");var c='<span class="highlight">'+a.match(b)+"</span>";return a.replace(b,c)}
function D(){fetch("ofudesaki.json").then(function(a){return a.json()}).then(function(a){(B=a)?((a=window.localStorage.getItem("ofudesaki-analysis"))&&(a=JSON.parse(a))&&(C=a),G("en_6th_ed",z),G("ro",A),I(C.selectedWordStr,z),J(C.selectedPartVerse,C.selectedWordStr),I(C.selectedRoWordStr,A),J(C.selectedRoPartVerse,C.selectedRoWordStr),C.isDataLoaded=!0,F()):alert("data not loaded")})}window.onunload=function(){C.isDataLoaded&&window.localStorage.setItem("ofudesaki-analysis",JSON.stringify(C))};
function L(a){for(var b=a.className.split(/\s+/),c=b.length,d=0;d<c;d++)if("active"===b[d]){b.splice(d,1);break}c===b.length&&b.push("active");a.className=b.join(" ")}(function(a,b){var c=b.getElementById("layout"),d=b.getElementById("menu"),e=b.getElementById("menuLink");a=b.getElementById("main");e.onclick=function(f){f.preventDefault();L(c);L(d);L(e)};a.onclick=function(f){-1!==d.className.indexOf("active")&&(f.preventDefault(),L(c),L(d),L(e))}})(window,window.document);
