var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ca(a,b){if(b){var c=ba;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ca("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,f=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var h=0;h<f&&c<d;)if(this[c++]!=b[h++])return!1;return h>=f}});
function da(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ea(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:da(a)}}
ca("Promise",function(a){function b(e){this.b=0;this.g=void 0;this.a=[];var g=this.c();try{e(g.resolve,g.reject)}catch(l){g.reject(l)}}function c(){this.a=null}function d(e){return e instanceof b?e:new b(function(g){g(e)})}if(a)return a;c.prototype.b=function(e){if(null==this.a){this.a=[];var g=this;this.c(function(){g.g()})}this.a.push(e)};var f=ba.setTimeout;c.prototype.c=function(e){f(e,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var e=this.a;this.a=[];for(var g=0;g<e.length;++g){var l=
e[g];e[g]=null;try{l()}catch(m){this.f(m)}}}this.a=null};c.prototype.f=function(e){this.c(function(){throw e;})};b.prototype.c=function(){function e(m){return function(n){l||(l=!0,m.call(g,n))}}var g=this,l=!1;return{resolve:e(this.v),reject:e(this.f)}};b.prototype.v=function(e){if(e===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof b)this.w(e);else{a:switch(typeof e){case "object":var g=null!=e;break a;case "function":g=!0;break a;default:g=!1}g?this.u(e):this.j(e)}};
b.prototype.u=function(e){var g=void 0;try{g=e.then}catch(l){this.f(l);return}"function"==typeof g?this.A(g,e):this.j(e)};b.prototype.f=function(e){this.l(2,e)};b.prototype.j=function(e){this.l(1,e)};b.prototype.l=function(e,g){if(0!=this.b)throw Error("Cannot settle("+e+", "+g+"): Promise already settled in state"+this.b);this.b=e;this.g=g;this.s()};b.prototype.s=function(){if(null!=this.a){for(var e=0;e<this.a.length;++e)h.b(this.a[e]);this.a=null}};var h=new c;b.prototype.w=function(e){var g=this.c();
e.i(g.resolve,g.reject)};b.prototype.A=function(e,g){var l=this.c();try{e.call(g,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(e,g){function l(t,w){return"function"==typeof t?function(V){try{m(t(V))}catch(W){n(W)}}:w}var m,n,u=new b(function(t,w){m=t;n=w});this.i(l(e,m),l(g,n));return u};b.prototype.catch=function(e){return this.then(void 0,e)};b.prototype.i=function(e,g){function l(){switch(m.b){case 1:e(m.g);break;case 2:g(m.g);break;default:throw Error("Unexpected state: "+
m.b);}}var m=this;null==this.a?h.b(l):this.a.push(l)};b.resolve=d;b.reject=function(e){return new b(function(g,l){l(e)})};b.race=function(e){return new b(function(g,l){for(var m=ea(e),n=m.next();!n.done;n=m.next())d(n.value).i(g,l)})};b.all=function(e){var g=ea(e),l=g.next();return l.done?d([]):new b(function(m,n){function u(V){return function(W){t[V]=W;w--;0==w&&m(t)}}var t=[],w=0;do t.push(void 0),w++,d(l.value).i(u(t.length-1),n),l=g.next();while(!l.done)})};return b});
var k=["verse","group","search","favorites"],fa=k.indexOf("verse"),ha=k.indexOf("group"),ia=k.indexOf("search"),p=k.indexOf("favorites"),q=document.getElementById("verseDisplay"),r=document.getElementById("partSelect"),v=document.getElementById("verseSelect"),x=document.getElementById("verseGroupSelect"),y=document.getElementById("verseNavTop"),z=document.getElementById("verseNavBottom"),ja=y.cloneNode(!0),A=document.getElementById("bookmarkDisplay"),B=document.getElementById("favoritesDisplay"),
ka=document.querySelector(".verse-options"),C=document.getElementById("searchTxt"),la=document.getElementById("searchBtn"),ma=document.getElementById("searchClearBtn"),D=document.getElementById("searchResults"),E=document.getElementById("groupView"),na=document.getElementById("hideButtonLabelCbx"),F={view:0,selectedPart:1,selectedVerse:1,selectedVerseGroup:"1:1-20",searchStr:"",hideButtonLabel:!1,verseOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1},
groupOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!1,showEnglish2:!1},searchOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1},favoritesOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1},isDataLoaded:!1},G={favorites:[],bookmark:0},H=null,I=null;
function oa(){r.onchange=function(){J(parseInt(r.value,10));K(1);L()};v.onchange=function(){K(parseInt(v.value,10));L()};x.onchange=function(){M(x.value);N()};M(F.selectedVerseGroup);J(F.selectedPart);K(F.selectedVerse);O(F.view);C.onkeyup=function(a){13===a.keyCode&&pa()};C.value=F.searchStr;la.onclick=function(){pa()};ma.onclick=function(){C.value="";C.focus()};qa()}
function qa(){var a=document.querySelector(".of-bottom-menu");F.hideButtonLabel&&ra(a,"of-hide-labels");na.checked=F.hideButtonLabel;na.onclick=function(){var b=F.hideButtonLabel;"undefined"===b&&(b=!1);F.hideButtonLabel=!b;na.checked=!b;b?sa(a,"of-hide-labels"):ra(a,"of-hide-labels");ta()}}function pa(){F.searchStr=C.value.trim();ua()}function P(){F.view===fa?L():F.view===ha?N():F.view===ia?ua():F.view===p&&va()}function J(a){F.selectedPart=a;r.value=F.selectedPart;wa(a)}
function K(a){F.selectedVerse=a;v.value=F.selectedVerse}function M(a){F.selectedVerseGroup=a;x.value=F.selectedVerseGroup}function xa(a){var b=H.verses.length;return 0>=a?H.verses[b-1]:a>b?H.verses[0]:H.verses[a-1]}function Q(a,b){for(var c=H.verses.length,d=0;d<c;d++){var f=H.verses[d];if(f.part===a&&f.verse===b)return f}return null}
function O(a){F.view=a;k.map(function(d){var f=document.getElementById(d+"View");f&&(f.style.display="none");f=document.querySelectorAll("."+d+"-view");for(var h=0;h<f.length;h++)f[h].style.display="none";(f=document.getElementById(d+"ViewMenuItem"))||console.error("ERROR: "+d+"ViewMenuItem not found.");sa(f,"selected")});a=k[a];var b=document.getElementById(a+"View"),c=document.querySelectorAll("."+a+"-view");b.style.display="";b.classList.add("animated","fadeIn");b.addEventListener("animationend",
function(){});for(b=0;b<c.length;b++)c[b].style.display="";ra(document.querySelector("#"+a+"ViewMenuItem"),"selected");ta();P()}function L(){y.style.display="";z.style.display="";var a=F.selectedPart,b=F.selectedVerse;(I=Q(a,b))?(ya(),q.innerHTML=R(I,"verse",null),S(q,I)):q.innerHTML="Verse "+a+":"+b+" not found!"}
function S(a,b){if(a&&b){var c=a.querySelector(".verse-btn"),d=a.querySelector(".read-btn"),f=a.querySelector(".favorite-btn"),h=a.querySelector(".bookmark-btn"),e=b.part,g=b.verse;if(e&&g){var l=e+":"+g;c&&(c.onclick=function(){J(e);K(g);O(fa)});if(d){var m=za(e,g);d.onclick=function(){M(m);O(ha);window.location.hash="verse"+e+"-"+g}}(a=-1<G.favorites.indexOf(l))&&f.classList.add("favorited");f.title=(a?"Remove from ":"Add to")+" Favorites";f.addEventListener("animationend",function(){f.classList.remove("animated",
"shake","tada");P()});l===G.bookmark?(h.classList.add("favorited"),h.title="Remove Bookmark"):h.title="Bookmark";h.addEventListener("animationend",function(){h.classList.remove("animated","pulse","tada");P()});f.onclick=function(){var n=G.favorites;-1<n.indexOf(l)?(n.splice(n.indexOf(l),1),f.classList.remove("favorited"),F.view===p?Aa(f.parentNode.parentNode.parentNode.parentNode.parentNode,function(){T();P()}):(f.classList.add("animated","shake"),T())):l.startsWith("undefined")?console.error("Tried to save an invalid verse."):
(n.push(l),n.sort(Ba),f.classList.add("favorited","animated","tada"),T())};h.onclick=function(){G.bookmark===l?(G.bookmark=!1,h.classList.remove("favorited"),F.view===p?Aa(h.parentNode.parentNode.parentNode.parentNode.parentNode,function(){T();P()}):(h.classList.add("animated","shake"),T())):G.bookmark!==l&&(G.bookmark=l,h.classList.add("favorited","animated","tada"),T())}}}else console.error("Verse element is invalid or selected verse was invalid.")}
function Aa(a,b){a&&(a.classList.add("animated","slideOutRight"),a.addEventListener("animationend",function(){a.classList.remove("animated","slideOutRight");b&&b()}))}function U(a){if(a&&-1<a.indexOf(":")){var b=a.split(":");a=parseInt(b[0],10);b=parseInt(b[1],10);if(a&&b)return{part:a,verse:b}}return null}function Ba(a,b){a=U(a);var c=U(b);return!a&&c?-1:a&&!c?1:a.part<c.part?-1:a.part>c.part?1:a.verse<b.verse?-1:a.verse>c.verse?1:0}
function za(a,b){if(a&&b){var c=H.verseGroups[a-1].groups;if(c)for(var d=0;d<c.length;d++){var f=c[d],h=f.split("-"),e=parseInt(h[1],10);if(b>=parseInt(h[0],10)&&b<=e)return a+":"+f}console.error("ERROR: getVerseGroupByPartVerse parameters ("+a+", "+b+") not found.");return null}console.error("ERROR: getVerseGroupByPartVerse parameters (part, verse) are not valid.")}
function N(){y.style.display="";z.style.display="";var a;if(a=F.selectedVerseGroup){a=a.split(":");var b=a[1],c=b.split("-");a={m:parseInt(a[0],10),B:parseInt(c[0],10),o:parseInt(c[1],10),C:b}}else a=null;if(a){E.innerHTML="";for(b=a.B;b<=a.o;b++){c=Q(a.m,b);var d=document.createElement("div");d.innerHTML=R(c,"group",null);S(d,c);E.appendChild(d)}b=a.m;var f="",h="";c=H.verseGroups[b-1];d=c.groups.length;for(var e=0;e<d;e++)a.C===c.groups[e]&&(0<e?f=b+":"+c.groups[e-1]:1===b?(f=H.verseGroups[16].groups,
f="17:"+f[f.length-1]):(f=b-1,h=H.verseGroups[f-1].groups,f=f+":"+h[h.length-1]),h=e<d-1?b+":"+c.groups[e+1]:17===b?"1:"+H.verseGroups[0].groups[0]:b+1+":"+H.verseGroups[b].groups[0]);Ca(f,h)}}
function va(){y.style.display="none";z.style.display="none";var a=G.bookmark,b=G.favorites;if(a){var c=U(G.bookmark);A.innerHTML="<h3>Bookmark</h3>"+R(Q(c.part,c.verse),"favorites","");S(A,c)}else A.innerHTML="";b&&0<b.length?(B.innerHTML='<h3 style="border-bottom: 1px solid gray;">Favorites</h3>',b.map(function(d){if(d=U(d)){var f=document.createElement("div");f.innerHTML=R(Q(d.part,d.verse),"favorites","");S(f,d);B.appendChild(f)}})):B.innerHTML="";a||b&&0!==b.length||(B.innerHTML="Bookmark and favorites have not been set.")}
function ua(){y.style.display="none";z.style.display="none";var a=F.searchStr;if(a){var b=0,c=[],d=H.verses.length;D.innerHTML="";for(var f=0;f<d;f++){var h=H.verses[f],e=new RegExp(a,"i"),g=document.createElement("div"),l=[];F.searchOptions.showRomanized&&l.push(h.ro);F.searchOptions.showJapanese&&l.push(h.jp1+h.jp2);F.searchOptions.showEnglish&&l.push(h.en_6th_ed);F.searchOptions.showPortuguese&&l.push(h.pt);F.searchOptions.showKanji&&l.push(h.kanji);l.join(" ").match(e)&&(b++,g.innerHTML=R(h,"search",
a),S(g,h),c.push(g))}d=document.createElement("div");d.innerHTML='<p>Search "'+a+'" yields '+b+" results.</p>";D.appendChild(d);for(a=0;a<c.length;a++)D.appendChild(c[a])}else D.innerHTML="<p>Enter a search term.</p>";C.select()}function Da(){var a=[];H.verseGroups.map(function(b){var c=b.part;a.push('<option value="" disabled="true">- Part '+c+" -</option>");b.groups.map(function(d){d=c+":"+d;a.push('<option value="'+d+'">'+d+"</option>")})});x.innerHTML=a.join("")}
function Ca(a,b){function c(){E.classList.add("animated","slideOutLeft");E.addEventListener("animationend",function(){M(b);N();E.className="";E.classList.add("animated","slideInRight");E.addEventListener("animationend",function(){E.className=""})})}function d(){E.classList.add("animated","slideOutRight");E.addEventListener("animationend",function(){M(a);N();E.className="";E.classList.add("animated","slideInLeft");E.addEventListener("animationend",function(){E.className=""})})}X(y,F.selectedVerseGroup,
d,c);X(z,F.selectedVerseGroup,d,c)}function ya(){function a(){J(f.part);K(f.verse);L()}function b(){J(d.part);K(d.verse);L()}var c="Verse "+I.part+":"+I.verse,d=xa(I.id-1),f=xa(I.id+1);X(y,c,b,a);X(z,c,b,a)}function X(a,b,c,d){a.innerHTML=ja.innerHTML;var f=a.getElementsByClassName("verse-nav-next-btn")[0],h=a.getElementsByClassName("verse-nav-middle")[0];a.getElementsByClassName("verse-nav-prev-btn")[0].onclick=c;f.onclick=d;h.innerHTML=b}
function R(a,b,c){c=c||!1;if(a){var d=a.part+":"+a.verse,f=Y(a.ro.split(/\s{2,}/g).join("<br/>"),c),h=Y(a.kanji.split(/\s{2,}/g).join("<br/>"),c),e=Y(a.en_6th_ed,c),g=Y(a.pt,c);c=Y(a.jp1+"<br/>"+a.jp2,c);return'<div class="verse-display">'+(F[b+"Options"].showRomanized?"<blockquote>"+f+"</blockquote>":"")+(F[b+"Options"].showJapanese?"<blockquote>"+c+"</blockquote>":"")+(F[b+"Options"].showEnglish?"<blockquote>"+e+"</blockquote>":"")+(F[b+"Options"].showPortuguese?"<blockquote>"+g+"</blockquote>":
"")+(F[b+"Options"].showKanji?"<blockquote>"+h+"</blockquote>":"")+'<table class="of-verse-controls"><tbody><tr><td><button class="favorite-btn btn circle" aria-label="Save verse to Favorites"><i class="fa fa-fw fa-star"></i></button><button class="bookmark-btn btn circle" aria-label="Bookmark verse in Favorites"><i class="fa fa-fw fa-bookmark"></i></button></td><td>'+(a.in_life_of_oyasama?'<span class="of-tag">Life of Oyasama</span>':"")+(a.in_doctrine?'<span class="of-tag">Doctrine</span>':"")+
"</td><td>"+d+"</td><td>"+("group"!==b?'<button class="read-btn btn circle" aria-label="View verse in Read" title="View verse in Read"><i class="fab fa-fw fa-readme"></i></button>':"")+("verse"!==b?'<button class="verse-btn btn circle" aria-label="View verse in Browse" title="View verse in Browse"><i class="fa fa-fw fa-eye"></i></button>':"")+"</td></tr></tbody></table></div>"}return"Verse not found."}
function Y(a,b){if(!b)return a;b=new RegExp(b,"i");var c='<span class="highlight">'+a.match(b)+"</span>";return a.replace(b,c)}
function Ea(){k.map(function(a){for(var b=ka.cloneNode(!0),c=b.querySelectorAll("input"),d=b.querySelectorAll("label"),f={},h=0;h<c.length;f={h:f.h},h++){var e=c[h],g=e.id.replace("-verse","-"+a);f.h=e.id.replace("-verse","").replace("show","").replace("Cbx","");e.id=g;e.onchange=function(l){return function(){var m=l.h,n=document.getElementById("show"+m+"Cbx-"+a);if(n){var u=F[a+"Options"]["show"+m];"undefined"===u&&(u=!1);F[a+"Options"]["show"+m]=!u;n.checked=!u}P()}}(f);e.checked=F[a+"Options"]["show"+
f.h]}for(c=0;c<d.length;c++)d[c].htmlFor=d[c].htmlFor.replace("-verse","-"+a);d=document.getElementById(a+"OptionsRow");d.innerHTML="";d.appendChild(b);document.getElementById(a+"ViewMenuItem").onclick=function(){O(k.indexOf(a))}})}function wa(a){var b=[];H.verses.map(function(c){c.part===parseInt(a,10)&&(c=c.verse,b.push('<option value="'+c+'"'+(F.selectedVerse===c?' selected="selected"':"")+">"+c+"</option>"))});v.innerHTML=b.join("");v.value=F.selectedVerse}
window.onload=function(){Fa().then(function(){return Ga("ofudesaki.json")}).then(function(a){H=JSON.parse(a.responseText);return Ga("keywords.json")}).then(function(a){JSON.parse(a.responseText);ta();a=[];for(var b=1;18>=b;b++)a.push('<option value="'+b+'">'+b+"</option>");r.innerHTML=a.join("");wa(F.selectedPart);Da();oa();Ea();F.isDataLoaded=!0}).catch(function(a){console.error("Something went wrong.",a)})};
function Fa(){return new Promise(function(a,b){var c=window.localStorage.getItem("ofudesaki-browser"),d=window.localStorage.getItem("ofudesaki-browser-favorites");c&&((c=JSON.parse(c))?(F=c,F.favoritesOptions||(F.favoritesOptions={showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1})):b(Error("Failed to load data from local storage.")));d&&((d=JSON.parse(d))?G=d:b(Error("Failed to load fav data from local storage.")));a("Data loaded from local storage.")})}
function ta(){window.localStorage.setItem("ofudesaki-browser",JSON.stringify(F))}function T(){window.localStorage.setItem("ofudesaki-browser-favorites",JSON.stringify(G))}function Ga(a){var b=void 0===b?"GET":b;var c=new XMLHttpRequest;return new Promise(function(d,f){c.onreadystatechange=function(){4===c.readyState&&(200<=c.status&&300>c.status?d(c):f({status:c.status,statusText:c.statusText}))};c.open(b||"GET",a,!0);c.send()})}
function Z(a){for(var b=a.className.split(/\s+/),c=b.length,d=0;d<c;d++)if("active"===b[d]){b.splice(d,1);break}c===b.length&&b.push("active");a.className=b.join(" ")}function sa(a,b){for(var c=a.className.split(/\s+/),d=c.length,f=0;f<d;f++)if(c[f]===b){c.splice(f,1);break}a.className=c.join(" ")}function ra(a,b){var c=a.className.split(/\s+/);c.push(b);a.className=c.join(" ")}
(function(a,b){var c=b.getElementById("layout"),d=b.getElementById("menu"),f=b.getElementById("menuLink");a=b.getElementById("main");f.onclick=function(h){h.preventDefault();Z(c);Z(d);Z(f)};a.onclick=function(h){-1!==d.className.indexOf("active")&&(h.preventDefault(),Z(c),Z(d),Z(f))}})(window,window.document);
