const f=["verse","group","search","favorites"],l=f.indexOf("verse"),m=f.indexOf("group"),aa=f.indexOf("search"),p=f.indexOf("favorites"),r=document.getElementById("verseDisplay"),t=document.getElementById("partSelect"),u=document.getElementById("verseSelect"),v=document.getElementById("verseGroupSelect"),w=document.getElementById("verseNavTop"),x=document.getElementById("verseNavBottom"),ba=w.cloneNode(!0),y=document.getElementById("bookmarkDisplay"),z=document.getElementById("favoritesDisplay"),
ca=document.querySelector(".verse-options"),A=document.getElementById("searchTxt"),da=document.getElementById("searchBtn"),ea=document.getElementById("searchClearBtn"),B=document.getElementById("searchResults"),C=document.getElementById("groupView");document.getElementById("favoritesView");const D=document.getElementById("hideButtonLabelCbx");
let E={view:0,selectedPart:1,selectedVerse:1,selectedVerseGroup:"1:1-20",searchStr:"",hideButtonLabel:!1,verseOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1},groupOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!1,showEnglish2:!1},searchOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1},favoritesOptions:{showRomanized:!0,showJapanese:!0,showEnglish:!0,
showPortuguese:!0,showKanji:!0,showEnglish2:!1},isDataLoaded:!1},F={favorites:[],bookmark:0},G=null,H=null;function fa(){t.onchange=function(){I(parseInt(t.value,10));J(1);K()};u.onchange=function(){J(parseInt(u.value,10));K()};v.onchange=function(){L(v.value);M()};L(E.selectedVerseGroup);I(E.selectedPart);J(E.selectedVerse);N(E.view);A.onkeyup=function(a){13===a.keyCode&&ha()};A.value=E.searchStr;da.onclick=function(){ha()};ea.onclick=function(){A.value="";A.focus()};ia()}
function ia(){const a=document.querySelector(".of-bottom-menu");E.hideButtonLabel&&O(a,"of-hide-labels");D.checked=E.hideButtonLabel;D.onclick=function(){let b=E.hideButtonLabel;"undefined"===b&&(b=!1);E.hideButtonLabel=!b;D.checked=!b;b?ja(a,"of-hide-labels"):O(a,"of-hide-labels");P()}}function ha(){E.searchStr=A.value.trim();ka()}function Q(){E.view===l?K():E.view===m?M():E.view===aa?ka():E.view===p&&la()}function I(a){E.selectedPart=a;t.value=E.selectedPart;ma(a)}
function J(a){E.selectedVerse=a;u.value=E.selectedVerse}function L(a){E.selectedVerseGroup=a;v.value=E.selectedVerseGroup}function na(a){let b=G.verses.length;return 0>=a?G.verses[b-1]:a>b?G.verses[0]:G.verses[a-1]}function S(a,b){let c=G.verses.length;for(let d=0;d<c;d++){const e=G.verses[d];if(e.part===a&&e.verse===b)return e}return null}
function N(a){E.view=a;f.map(d=>{var e=document.getElementById(d+"View");e&&(e.style.display="none");e=document.querySelectorAll("."+d+"-view");for(let g=0;g<e.length;g++)e[g].style.display="none";(e=document.getElementById(d+"ViewMenuItem"))||console.error("ERROR: "+d+"ViewMenuItem not found.");ja(e,"selected")});a=f[a];var b=document.getElementById(a+"View");const c=document.querySelectorAll("."+a+"-view");b.style.display="";b.classList.add("animated","fadeIn");b.addEventListener("animationend",
function(){});for(b=0;b<c.length;b++)c[b].style.display="";O(document.querySelector("#"+a+"ViewMenuItem"),"selected");P();Q()}function K(){w.style.display="";x.style.display="";const a=E.selectedPart,b=E.selectedVerse;(H=S(a,b))?(oa(),r.innerHTML=T(H,"verse",null),U(r,H)):r.innerHTML="Verse "+a+":"+b+" not found!"}
function U(a,b){if(a&&b){var c=a.querySelector(".verse-btn"),d=a.querySelector(".read-btn"),e=a.querySelector(".favorite-btn"),g=a.querySelector(".bookmark-btn"),h=b.part,n=b.verse;if(h&&n){var k=h+":"+n;c&&(c.onclick=()=>{I(h);J(n);N(l)});if(d){const q=pa(h,n);d.onclick=()=>{L(q);N(m);window.location.hash="verse"+h+"-"+n}}(a=-1<F.favorites.indexOf(k))&&e.classList.add("favorited");e.title=(a?"Remove from ":"Add to")+" Favorites";e.addEventListener("animationend",()=>{e.classList.remove("animated",
"shake","tada");Q()});k===F.bookmark?(g.classList.add("favorited"),g.title="Remove Bookmark"):g.title="Bookmark";g.addEventListener("animationend",()=>{g.classList.remove("animated","pulse","tada");Q()});e.onclick=function(){const q=F.favorites;-1<q.indexOf(k)?(q.splice(q.indexOf(k),1),e.classList.remove("favorited"),E.view===p?qa(e.parentNode.parentNode.parentNode.parentNode.parentNode,()=>{V();Q()}):(e.classList.add("animated","shake"),V())):k.startsWith("undefined")?console.error("Tried to save an invalid verse."):
(q.push(k),q.sort(ra),e.classList.add("favorited","animated","tada"),V())};g.onclick=function(){F.bookmark===k?(F.bookmark=!1,g.classList.remove("favorited"),E.view===p?qa(g.parentNode.parentNode.parentNode.parentNode.parentNode,()=>{V();Q()}):(g.classList.add("animated","shake"),V())):F.bookmark!==k&&(F.bookmark=k,g.classList.add("favorited","animated","tada"),V())}}}else console.error("Verse element is invalid or selected verse was invalid.")}
function qa(a,b){a&&(a.classList.add("animated","slideOutRight"),a.addEventListener("animationend",function(){a.classList.remove("animated","slideOutRight");b&&b()}))}function W(a){if(a&&-1<a.indexOf(":")){var b=a.split(":");a=parseInt(b[0],10);b=parseInt(b[1],10);if(a&&b)return{part:a,verse:b}}return null}function ra(a,b){a=W(a);const c=W(b);return!a&&c?-1:a&&!c?1:a.part<c.part?-1:a.part>c.part?1:a.verse<b.verse?-1:a.verse>c.verse?1:0}
function pa(a,b){if(a&&b){var c=G.verseGroups[a-1].groups;if(c)for(let d=0;d<c.length;d++){const e=c[d],g=e.split("-"),h=parseInt(g[1],10);if(b>=parseInt(g[0],10)&&b<=h)return a+":"+e}console.error("ERROR: getVerseGroupByPartVerse parameters ("+a+", "+b+") not found.");return null}console.error("ERROR: getVerseGroupByPartVerse parameters (part, verse) are not valid.")}
function M(){w.style.display="";x.style.display="";var a;if(a=E.selectedVerseGroup){a=a.split(":");var b=a[1],c=b.split("-");a={g:parseInt(a[0],10),i:parseInt(c[0],10),h:parseInt(c[1],10),j:b}}else a=null;if(a){C.innerHTML="";for(b=a.i;b<=a.h;b++){c=S(a.g,b);var d=document.createElement("div");d.innerHTML=T(c,"group",null);U(d,c);C.appendChild(d)}b=a.g;var e="",g="";c=G.verseGroups[b-1];d=c.groups.length;for(let h=0;h<d;h++)a.j===c.groups[h]&&(0<h?e=b+":"+c.groups[h-1]:1===b?(e=G.verseGroups[16].groups,
e="17:"+e[e.length-1]):(e=b-1,g=G.verseGroups[e-1].groups,e=e+":"+g[g.length-1]),g=h<d-1?b+":"+c.groups[h+1]:17===b?"1:"+G.verseGroups[0].groups[0]:b+1+":"+G.verseGroups[b].groups[0]);sa(e,g)}}
function la(){w.style.display="none";x.style.display="none";const a=F.bookmark,b=F.favorites;if(a){const c=W(F.bookmark);y.innerHTML="<h3>Bookmark</h3>"+T(S(c.part,c.verse),"favorites","");U(y,c)}else y.innerHTML="";b&&0<b.length?(z.innerHTML='<h3 style="border-bottom: 1px solid gray;">Favorites</h3>',b.map(c=>{if(c=W(c)){const d=document.createElement("div");d.innerHTML=T(S(c.part,c.verse),"favorites","");U(d,c);z.appendChild(d)}})):z.innerHTML="";a||b&&0!==b.length||(z.innerHTML="Bookmark and favorites have not been set.")}
function ka(){w.style.display="none";x.style.display="none";var a=E.searchStr;if(a){let c=0,d=[];var b=G.verses.length;B.innerHTML="";for(let e=0;e<b;e++){const g=G.verses[e],h=new RegExp(a,"i"),n=document.createElement("div"),k=[];E.searchOptions.showRomanized&&k.push(g.ro);E.searchOptions.showJapanese&&k.push(g.jp1+g.jp2);E.searchOptions.showEnglish&&k.push(g.en_6th_ed);E.searchOptions.showPortuguese&&k.push(g.pt);E.searchOptions.showKanji&&k.push(g.kanji);k.join(" ").match(h)&&(c++,n.innerHTML=
T(g,"search",a),U(n,g),d.push(n))}b=document.createElement("div");b.innerHTML='<p>Search "'+a+'" yields '+c+" results.</p>";B.appendChild(b);for(a=0;a<d.length;a++)B.appendChild(d[a])}else B.innerHTML="<p>Enter a search term.</p>";A.select()}function ta(){let a=[];G.verseGroups.map(function(b){const c=b.part;a.push('<option value="" disabled="true">- Part '+c+" -</option>");b.groups.map(function(d){d=c+":"+d;a.push('<option value="'+d+'">'+d+"</option>")})});v.innerHTML=a.join("")}
function sa(a,b){function c(){C.classList.add("animated","slideOutLeft");C.addEventListener("animationend",function(){L(b);M();C.className="";C.classList.add("animated","slideInRight");C.addEventListener("animationend",function(){C.className=""})})}function d(){C.classList.add("animated","slideOutRight");C.addEventListener("animationend",function(){L(a);M();C.className="";C.classList.add("animated","slideInLeft");C.addEventListener("animationend",function(){C.className=""})})}X(w,E.selectedVerseGroup,
d,c);X(x,E.selectedVerseGroup,d,c)}function oa(){function a(){I(e.part);J(e.verse);K()}function b(){I(d.part);J(d.verse);K()}var c="Verse "+H.part+":"+H.verse;const d=na(H.id-1),e=na(H.id+1);X(w,c,b,a);X(x,c,b,a)}function X(a,b,c,d){a.innerHTML=ba.innerHTML;const e=a.getElementsByClassName("verse-nav-next-btn")[0],g=a.getElementsByClassName("verse-nav-middle")[0];a.getElementsByClassName("verse-nav-prev-btn")[0].onclick=c;e.onclick=d;g.innerHTML=b}
function T(a,b,c){c=c||!1;if(a){const d=a.part+":"+a.verse,e=Y(a.ro.split(/\s{2,}/g).join("<br/>"),c),g=Y(a.kanji.split(/\s{2,}/g).join("<br/>"),c),h=Y(a.en_6th_ed,c),n=Y(a.pt,c);c=Y(a.jp1+"<br/>"+a.jp2,c);return'<div class="verse-display">'+(E[b+"Options"].showRomanized?"<blockquote>"+e+"</blockquote>":"")+(E[b+"Options"].showJapanese?"<blockquote>"+c+"</blockquote>":"")+(E[b+"Options"].showEnglish?"<blockquote>"+h+"</blockquote>":"")+(E[b+"Options"].showPortuguese?"<blockquote>"+n+"</blockquote>":
"")+(E[b+"Options"].showKanji?"<blockquote>"+g+"</blockquote>":"")+'<table class="of-verse-controls"><tbody><tr><td><button class="favorite-btn btn circle" aria-label="Save verse to Favorites"><i class="fa fa-fw fa-star"></i></button><button class="bookmark-btn btn circle" aria-label="Bookmark verse in Favorites"><i class="fa fa-fw fa-bookmark"></i></button></td><td>'+(a.in_life_of_oyasama?'<span class="of-tag">Life of Oyasama</span>':"")+(a.in_doctrine?'<span class="of-tag">Doctrine</span>':"")+
"</td><td>"+d+"</td><td>"+("group"!==b?'<button class="read-btn btn circle" aria-label="View verse in Read" title="View verse in Read"><i class="fab fa-fw fa-readme"></i></button>':"")+("verse"!==b?'<button class="verse-btn btn circle" aria-label="View verse in Browse" title="View verse in Browse"><i class="fa fa-fw fa-eye"></i></button>':"")+"</td></tr></tbody></table></div>"}return"Verse not found."}
function Y(a,b){if(!b)return a;b=new RegExp(b,"i");const c='<span class="highlight">'+a.match(b)+"</span>";return a.replace(b,c)}
function ua(){f.map(function(a){const b=ca.cloneNode(!0);var c=b.querySelectorAll("input"),d=b.querySelectorAll("label");for(let e=0;e<c.length;e++){const g=c[e],h=g.id.replace("-verse","-"+a),n=g.id.replace("-verse","").replace("show","").replace("Cbx","");g.id=h;g.onchange=function(){var k=n;const q=document.getElementById("show"+k+"Cbx-"+a);if(q){let R=E[a+"Options"]["show"+k];"undefined"===R&&(R=!1);E[a+"Options"]["show"+k]=!R;q.checked=!R}Q()};g.checked=E[a+"Options"]["show"+n]}for(c=0;c<d.length;c++)d[c].htmlFor=
d[c].htmlFor.replace("-verse","-"+a);d=document.getElementById(a+"OptionsRow");d.innerHTML="";d.appendChild(b);document.getElementById(a+"ViewMenuItem").onclick=function(){N(f.indexOf(a))}})}function ma(a){let b=[];G.verses.map(function(c){c.part===parseInt(a,10)&&(c=c.verse,b.push('<option value="'+c+'"'+(E.selectedVerse===c?' selected="selected"':"")+">"+c+"</option>"))});u.innerHTML=b.join("");u.value=E.selectedVerse}
window.onload=function(){va().then(function(){return wa("ofudesaki.json")}).then(function(a){G=JSON.parse(a.responseText);return wa("keywords.json")}).then(function(a){JSON.parse(a.responseText);P();a=[];for(let b=1;18>=b;b++)a.push('<option value="'+b+'">'+b+"</option>");t.innerHTML=a.join("");ma(E.selectedPart);ta();fa();ua();E.isDataLoaded=!0}).catch(function(a){console.error("Something went wrong.",a)})};
function va(){return new Promise(function(a,b){var c=window.localStorage.getItem("ofudesaki-browser"),d=window.localStorage.getItem("ofudesaki-browser-favorites");c&&((c=JSON.parse(c))?(E=c,E.favoritesOptions||(E.favoritesOptions={showRomanized:!0,showJapanese:!0,showEnglish:!0,showPortuguese:!0,showKanji:!0,showEnglish2:!1})):b(Error("Failed to load data from local storage.")));d&&((d=JSON.parse(d))?F=d:b(Error("Failed to load fav data from local storage.")));a("Data loaded from local storage.")})}
function P(){window.localStorage.setItem("ofudesaki-browser",JSON.stringify(E))}function V(){window.localStorage.setItem("ofudesaki-browser-favorites",JSON.stringify(F))}function wa(a){var b=new XMLHttpRequest;return new Promise(function(c,d){b.onreadystatechange=function(){4===b.readyState&&(200<=b.status&&300>b.status?c(b):d({status:b.status,statusText:b.statusText}))};b.open("GET",a,!0);b.send()})}
function Z(a){let b=a.className.split(/\s+/),c=b.length;for(let d=0;d<c;d++)if("active"===b[d]){b.splice(d,1);break}c===b.length&&b.push("active");a.className=b.join(" ")}function ja(a,b){let c=a.className.split(/\s+/),d=c.length;for(let e=0;e<d;e++)if(c[e]===b){c.splice(e,1);break}a.className=c.join(" ")}function O(a,b){let c=a.className.split(/\s+/);c.push(b);a.className=c.join(" ")}
(function(a,b){var c=b.getElementById("layout"),d=b.getElementById("menu"),e=b.getElementById("menuLink");a=b.getElementById("main");e.onclick=function(g){g.preventDefault();Z(c);Z(d);Z(e)};a.onclick=function(g){-1!==d.className.indexOf("active")&&(g.preventDefault(),Z(c),Z(d),Z(e))}})(window,window.document);
