var x=[{a:"\ud83e\udd16",name:"Robot"},{a:"\ud83d\udc69\u200d\ud83d\udcbb",name:"Woman Technologist"},{a:"\ud83d\udc68\u200d\ud83d\udcbb",name:"Man Technologist"},{a:"\ud83c\udfdd\ufe0f",name:"Desert Island"},{a:"\ud83d\ude80",name:"Rocket"},{a:"\ud83d\udef8",name:"Flying Saucer"},{a:"\ud83d\udcd4",name:"Notebook with Decorative Cover"},{a:"\ud83d\udcd5",name:"Closed Book"},{a:"\ud83d\udcd6",name:"Open Book"},{a:"\ud83d\udcd7",name:"Green Book"},{a:"\ud83d\udcd8",name:"Blue Book"},{a:"\ud83d\udcd9",
name:"Orange Book"},{a:"\ud83d\udcda",name:"Books"},{a:"\ud83d\udcd3",name:"Notebook"},{a:"\ud83d\udcd2",name:"Ledger"},{a:"\ud83d\udcc3",name:"Page with Curl"},{a:"\ud83d\udcdc",name:"Scroll"},{a:"\ud83d\udcc4",name:"Page Facing Up"},{a:"\ud83d\udcf0",name:"Newspaper"},{a:"\ud83d\uddde\ufe0f Rolled-Up",name:"Newspaper"},{a:"\ud83d\udcd1",name:"Bookmark Tabs"},{a:"\ud83d\udd16",name:"Bookmark"},{a:"\ud83c\udff7\ufe0f",name:"Label"},{a:"\ud83d\udcb0",name:"Money Bag"},{a:"\ud83d\udd0d",name:"Magnifying Glass Tilted Left"},
{a:"\ud83d\udd0e",name:"Magnifying Glass Tilted Right"},{a:"\ud83d\udd6f\ufe0f",name:"Candle"},{a:"\ud83d\udca1",name:"Light Bulb"},{a:"\ud83d\udcfa",name:"Television"},{a:"\ud83d\udcf7",name:"Camera"},{a:"\ud83d\udcbb",name:"Laptop"},{a:"\ud83d\udda5\ufe0f",name:"Desktop Computer"},{a:"\ud83d\udda8\ufe0f",name:"Printer"},{a:"\u2328\ufe0f",name:"Keyboard"},{a:"\ud83d\uddb1\ufe0f",name:"Computer Mouse"},{a:"\u2764\ufe0f",name:"Red Heart"},{a:"\ud83e\udd7a",name:"Pleading Face"},{a:"\u2728",name:"Sparkles"},
{a:"\ud83d\udd25",name:"Fire"},{a:"\ud83d\ude0a",name:"Smiling Face with Smiling Eyes"},{a:"\ud83e\udd70",name:"Smiling Face with Hearts"},{a:"\ud83c\udf83",name:"Jack-O-Lantern"},{a:"\ud83d\udc4d",name:"Thumbs Up"},{a:"\ud83d\uddfa\ufe0f",name:"World Map"},{a:"\ud83d\uddbc\ufe0f",name:"Framed Picture"},{a:"\ud83d\udcf1",name:"Mobile Phone"},{a:"\ud83c\udf89",name:"Party Popper"},{a:"\ud83c\udf8a",name:"Confetti Ball"},{a:"\u231a",name:"Watch"},{a:"\u23f0",name:"Alarm Clock"},{a:"\u23f1\ufe0f",name:"Stopwatch"},
{a:"\u23f2\ufe0f",name:"Timer Clock"},{a:"\ud83d\udd70\ufe0f",name:"Mantelpiece Clock"},{a:"\ud83c\udfb8",name:"Guitar"},{a:"\ud83c\udfb9",name:"Musical Keyboard"},{a:"\ud83c\udfba",name:"Trumpet"},{a:"\ud83c\udfbb",name:"Violin"},{a:"\ud83e\udd41",name:"Drum"},{a:"\ud83c\udfac",name:"Clapper Board"},{a:"\ud83c\udff9",name:"Bow and Arrow"},{a:"\ud83c\udfb1",name:"Pool 8 Ball"},{a:"\ud83c\udfae",name:"Video Game"},{a:"\ud83c\udfb0",name:"Slot Machine"},{a:"\ud83c\udfb2",name:"Game Die"},{a:"\u265f\ufe0f",
name:"Chess Pawn"},{a:"\ud83c\udfad",name:"Performing Arts"},{a:"\ud83c\udfa8",name:"Artist Palette"},{a:"\ud83c\udfbc",name:"Musical Score"},{a:"\ud83c\udfa4",name:"Microphone"},{a:"\ud83c\udfa7",name:"Headphone"},{a:"\ud83c\udfaf",name:"Direct Hit"},{a:"\u26bd",name:"Soccer Ball"},{a:"\u26be",name:"Baseball"},{a:"\ud83c\udfc0",name:"Basketball"},{a:"\ud83c\udfd0",name:"Volleyball"},{a:"\ud83c\udfc8",name:"American Football"},{a:"\ud83c\udfc9",name:"Rugby Football"},{a:"\ud83c\udfbe",name:"Tennis"},
{a:"\ud83c\udfb3",name:"Bowling"},{a:"\ud83c\udf9f\ufe0f",name:"Admission Tickets"},{a:"\ud83c\udfab",name:"Ticket"},{a:"\ud83c\udf96\ufe0f",name:"Military Medal"},{a:"\ud83c\udfc6",name:"Trophy"},{a:"\ud83c\udfc5",name:"Sports Medal"},{a:"\ud83e\udd47",name:"1st Place Medal"},{a:"\u2615",name:"Hot Beverage"},{a:"\ud83c\udf54",name:"Hamburger"},{a:"\ud83c\udf5f",name:"French Fries"},{a:"\ud83c\udf55",name:"Pizza"},{a:"\ud83e\udd5e",name:"Pancakes"},{a:"\ud83e\uddc7",name:"Waffle"},{a:"\ud83e\uddc0",
name:"Cheese Wedge"},{a:"\ud83c\udf56",name:"Meat on Bone"},{a:"\ud83e\udd65",name:"Coconut"},{a:"\ud83e\udd5d",name:"Kiwi Fruit"},{a:"\ud83c\udf45",name:"Tomato"},{a:"\ud83c\udf4a",name:"Tangerine"},{a:"\ud83c\udf4b",name:"Lemon"},{a:"\ud83c\udf4c",name:"Banana"},{a:"\ud83c\udf4d",name:"Pineapple"},{a:"\ud83e\udd6d",name:"Mango"},{a:"\ud83c\udf4e",name:"Red Apple"},{a:"\ud83c\udf4f",name:"Green Apple"},{a:"\ud83c\udf50",name:"Pear"},{a:"\ud83c\udf51",name:"Peach"},{a:"\ud83c\udf52",name:"Cherries"},
{a:"\ud83c\udf53",name:"Strawberry"},{a:"\ud83c\udf08",name:"Rainbow"},{a:"\u2602\ufe0f",name:"Umbrella"},{a:"\u2614",name:"Umbrella with Rain Drops"},{a:"\u26a1",name:"High Voltage"},{a:"\u2744\ufe0f",name:"Snowflake"},{a:"\u2603\ufe0f",name:"Snowman"},{a:"\u26c4",name:"Snowman Without Snow"},{a:"\u2604\ufe0f",name:"Comet"},{a:"\ud83d\udd25",name:"Fire"},{a:"\ud83d\udca7",name:"Droplet"},{a:"\ud83c\udf0a",name:"Water Wave"},{a:"\ud83c\udf84",name:"Christmas Tree"},{a:"\ud83c\udf8b",name:"Tanabata Tree"},
{a:"\ud83c\udf8d",name:"Pine Decoration"},{a:"\u2b50",name:"Star"},{a:"\ud83c\udf1f",name:"Glowing Star"},{a:"\ud83c\udf20",name:"Shooting Star"},{a:"\u2601\ufe0f",name:"Cloud"},{a:"\ud83d\ude48 See-No-Evil",name:"Monkey"},{a:"\ud83d\ude49 Hear-No-Evil",name:"Monkey"},{a:"\ud83d\ude4a Speak-No-Evil",name:"Monkey"},{a:"\ud83d\udca5",name:"Collision"},{a:"\ud83d\udcab",name:"Dizzy"},{a:"\ud83d\udca6",name:"Sweat Droplets"},{a:"\ud83d\udca8",name:"Dashing Away"},{a:"\ud83d\udc35",name:"Monkey Face"},
{a:"\ud83d\udc12",name:"Monkey"},{a:"\ud83e\udd8d",name:"Gorilla"},{a:"\ud83e\udda7",name:"Orangutan"},{a:"\ud83d\udc36",name:"Dog Face"},{a:"\ud83d\udc15",name:"Dog"},{a:"\ud83e\uddae",name:"Guide Dog"},{a:"\ud83d\udc15\u200d\ud83e\uddba",name:"Service Dog"},{a:"\ud83d\udc29",name:"Poodle"},{a:"\ud83d\udc3a",name:"Wolf"},{a:"\ud83e\udd8a",name:"Fox"},{a:"\ud83e\udd9d",name:"Raccoon"},{a:"\ud83d\udc31",name:"Cat Face"},{a:"\ud83e\udd81",name:"Lion"},{a:"\ud83d\udc2f",name:"Tiger Face"},{a:"\ud83e\udd84",
name:"Unicorn"},{a:"\ud83e\udd93",name:"Zebra"},{a:"\ud83d\udc2e",name:"Cow Face"},{a:"\ud83d\udc37",name:"Pig Face"},{a:"\ud83d\udc16",name:"Pig"},{a:"\ud83d\udc17",name:"Boar"},{a:"\ud83d\udc2d",name:"Mouse Face"},{a:"\ud83d\udc3b",name:"Bear"},{a:"\ud83d\udc28",name:"Koala"},{a:"\ud83d\udc3c",name:"Panda"},{a:"\ud83d\udc14",name:"Chicken"},{a:"\ud83d\udc13",name:"Rooster"},{a:"\ud83d\udc23",name:"Hatching Chick"},{a:"\ud83e\udd89",name:"Owl"},{a:"\ud83d\udc38",name:"Frog"},{a:"\ud83d\udc1f",name:"Fish"},
{a:"\ud83d\udc20",name:"Tropical Fish"},{a:"\ud83d\udc21",name:"Blowfish"},{a:"\ud83e\udd88",name:"Shark"},{a:"\ud83d\udc19",name:"Octopus"},{a:"\ud83d\udc1a",name:"Spiral Shell"},{a:"\ud83d\udc0c",name:"Snail"},{a:"\ud83e\udd8b",name:"Butterfly"},{a:"\ud83d\udc1b",name:"Bug"},{a:"\ud83d\udc1c",name:"Ant"},{a:"\ud83d\udc1d",name:"Honeybee"},{a:"\ud83d\udc1e",name:"Lady Beetle"},{a:"\ud83d\udd77\ufe0f",name:"Spider"},{a:"\ud83d\udd78\ufe0f",name:"Spider Web"},{a:"\ud83c\udf3a",name:"Hibiscus"},{a:"\ud83c\udf3b",
name:"Sunflower"},{a:"\ud83c\udf3c",name:"Blossom"},{a:"\ud83c\udf37",name:"Tulip"},{a:"\ud83c\udf31",name:"Seedling"},{a:"\ud83c\udf32",name:"Evergreen Tree"},{a:"\ud83c\udf33",name:"Deciduous Tree"},{a:"\ud83c\udf34",name:"Palm Tree"},{a:"\ud83c\udf35",name:"Cactus"},{a:"\ud83c\udf3e",name:"Sheaf of Rice"},{a:"\ud83c\udf3f",name:"Herb"},{a:"\u2618\ufe0f",name:"Shamrock"},{a:"\ud83c\udf40",name:"Four Leaf Clover"},{a:"\ud83c\udf41",name:"Maple Leaf"},{a:"\ud83c\udf0d",name:"Globe Showing Europe-Africa"},
{a:"\ud83c\udf0e",name:"Globe Showing Americas"},{a:"\ud83c\udf0f",name:" Globe Showing Asia-Australia"},{a:"\ud83c\udf10",name:" Globe with Meridians"}];(function(){function r(){window.localStorage.setItem("meta-tags-gen",JSON.stringify(e))}function y(a){var b=window.localStorage.getItem("meta-tags-gen");b&&(b=JSON.parse(b))&&(e=b,a&&a())}function g(a,b,c,m){if(a&&(a=a.querySelectorAll("."+b),c=(c=c[b])?c:"",a)){var l,p=a.length;for(l=0;l<p;l++){var d=a[l];if("I"===d.tagName)d.className=b+" "+("TRUE"===c?"far fa-check-square":"far fa-square");else if("INPUT"===d.tagName||"TEXTAREA"===d.tagName)"checkbox"===d.getAttribute("type")?d.checked="TRUE"===
c:d.value=c;else if("SELECT"===d.tagName){var k=d.querySelectorAll("option"),n,z=k.length,v=-1;for(n=0;n<z;n++)if(c===k[n].value){k[n].selected=!0;v=n;break}d.value=c;d.selectedIndex=v;if(k=d)"function"===typeof Event?d=new Event("change"):(d=document.createEvent("Event"),d.initEvent("change",!0,!0)),k.dispatchEvent(d)}else c&&""!==(c+"").trim()?c=c.replace(/\n/g,"<br/>").replace(/\s\s/g,"&nbsp;"):c=m?"":"N/A",d.innerHTML=c}}}function h(a,b,c){if(a=a.querySelector("."+b)){var m="checkbox"===a.getAttribute("type");
c[b]=m?a.checked?"TRUE":"FALSE":a.value}else c[b]=""}function t(a){var b={};h(a,"emoji",b);h(a,"title",b);h(a,"description",b);h(a,"keywords",b);h(a,"author",b);h(a,"url",b);h(a,"imageUrl",b);h(a,"twitter",b);h(a,"fbAppId",b);b.url&&(b.f=A(b.url));b.c&&(b.b=b.c.trim().split(",").map(function(c){return"#"+c.replace(/[^\d\w_]/g,"")}).join(" "));return b}function A(a){a=a.split("/")[-1<a.indexOf("//")?2:0];a=a.split(":")[0];return a.split("?")[0]}function u(a,b){var c=f.querySelector("."+a);c.onblur=
c.onkeyup=c.onchange=c.onload=function(){return w(a,b)};w(a,b)}function w(a,b){var c=b-f.querySelector("."+a).value.length;f.querySelector("."+a+"-char-count").innerHTML=(0>c?'<span class="text-danger">'+c+"</span>":c)+" of "+b+" chars left"}function B(){f.querySelector(".emoji").innerHTML=x.map(function(a){return'<option value="'+a.a+'">'+a.a+" "+a.name+"</option>"}).join("")}var f=document.getElementById("metaInputs"),q=document.getElementById("output"),C=document.getElementById("generateBtn"),
D=document.getElementById("genTwitterPostBtn"),E=document.getElementById("genFacebookPostBtn"),F=document.getElementById("copyOutputBtn"),G=document.getElementById("navbarToggleBtn"),e={};window.onload=function(){B();y(function(){var a=e;g(f,"emoji",a,!0);g(f,"title",a,!0);g(f,"description",a,!0);g(f,"keywords",a,!0);g(f,"author",a,!0);g(f,"url",a,!0);g(f,"imageUrl",a,!0);g(f,"twitter",a,!0);g(f,"fbAppId",a,!0);u("title",70);u("description",160);u("keywords",160)});C.onclick=function(){e=t(f);r();
var a=e.emoji,b=e.title,c=e.description,m=e.keywords,l=e.author,p=e.imageUrl,d=e.twitter,k=e.fbAppId;q.innerHTML='<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=edge"/>\n<meta name="viewport" content="width=device-width, initial-scale=1"/>\n\n<title>'+b+"</title>\n"+(l?'<meta name="author" content="'+l+'">':"")+"\n"+(c?'<meta name="description" content="'+c+'">':"")+"\n"+(m?'<meta name="keywords" content="'+m+'">':"")+'\n\n\x3c!-- Twitter --\x3e\n<meta name="twitter:card" content="summary_large_image">\n<meta name="twitter:title" content="'+
a+" "+b+'">\n<meta name="twitter:description" content="'+c+'">\n<meta name="twitter:site" content="@'+d+'">\n<meta name="twitter:creator" content="@'+d+'">\n<meta name="twitter:image" content="'+p+'">\n\n\x3c!-- Open Graph general (Facebook, Pinterest)--\x3e\n<meta property="og:title" content="'+a+" "+b+'">\n<meta property="og:description" content="'+c+'">\n<meta property="og:url" content="'+e.url+'">\n<meta property="og:site_name" content="'+e.siteName+'">\n<meta property="og:type" content="website">\n<meta property="og:image" content="'+
p+'">\n\n'+(k?'<meta property="fb:app_id" content="'+k+'">\n':"")+"\n\x3c!-- https://realfavicongenerator.net --\x3e\n\n\x3c!-- CSS --\x3e\n";window.location="#outputSection"};D.onclick=function(){e=t(f);r();var a=e;q.innerHTML=a.a+" "+a.title+"\n"+a.description+"\n\ud83c\udff7\ufe0f "+a.b+"\n"+a.url+"\n";window.location="#outputSection"};E.onclick=function(){e=t(f);r();var a=e;q.innerHTML=a.a+" "+a.title+"\n"+a.description+"\n\ud83c\udff7\ufe0f "+a.b+"\n\ud83d\udc4d Follow me @"+a.g+"\n"+a.url+"\n";
window.location="#outputSection"};F.onclick=function(){q.select();document.execCommand("copy")};G.onclick=function(){document.getElementById("navbarResponsive").classList.toggle("show")}}})();
