var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(c,b,g){c!=Array.prototype&&c!=Object.prototype&&(c[b]=g.value)};function ba(c){c=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,c];for(var b=0;b<c.length;++b){var g=c[b];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");}var ca=ba(this);
function da(c,b){if(b){var g=ca;c=c.split(".");for(var l=0;l<c.length-1;l++){var q=c[l];q in g||(g[q]={});g=g[q]}c=c[c.length-1];l=g[c];b=b(l);b!=l&&null!=b&&aa(g,c,{configurable:!0,writable:!0,value:b})}}da("Array.prototype.fill",function(c){return c?c:function(b,g,l){var q=this.length||0;0>g&&(g=Math.max(0,q+g));if(null==l||l>q)l=q;l=Number(l);0>l&&(l=Math.max(0,q+l));for(g=Number(g||0);g<l;g++)this[g]=b;return this}});
var t=function(){function c(p){g();var r=b(p);r&&(r.play(),r.loop=!0,r.volume=.1);q=p}function b(p){if(!p)return null;var r=v[p];return r?r:(console.error("Sound '"+p+"' not found"),null)}function g(){var p=b(q);p&&p.pause()}var l=null,q=null,v=null,G={addPart:"addPart - Jump 1.wav",clear:"clear - Select 1.wav",endGame:"endGame - Victory SoundFX2.ogg",match:"match - Fruit collect 1.wav",noMatch:"noMatch - Text 1.wav",gameBgMusic:"game - POL-star-way-short.wav",menuBgMusic:"menu - POL-follow-me-short.wav"};
return{m:function(p){if(!v){v={};for(var r in G)v[r]=new Audio("./audio/"+G[r])}p()},u:g,s:function(){c(q)},play:function(p){if(l){var r=b(l);r&&(r.currentTime=0,r.pause())}(r=b(p))&&r.play();l=p},o:c}}();function z(c){return c[Math.floor(Math.random()*c.length)]};function C(c,b){this.text=c;this.x=b.x;this.y=b.y;this.b=b.b;this.a=b.a;this.font=b.font;this.fontSize=b.fontSize;this.color=b.color;this.mode=b.mode;this.hidden=!1;this.c=b.c||"both";this.g=b.g;this.position=b.position;this.onclick=b.onclick};var N={text:function(c,b){var g=b.align||"center",l=b.opacity||1,q=b.x,v=b.y;D.font=b.fontSize+"px "+(b.fontStyle||"Arial");D.fillStyle=b.color;D.globalAlpha=l;b=D.measureText(c);"center"===g?q-=b.width/2:"right"===g&&(q-=b.width);D.fillText(c,q,v);D.globalAlpha=1},clear:function(c){D.fillStyle=c||"white";D.clearRect(0,0,J.width,J.height);D.fillRect(0,0,J.width,J.height)},l:function(c){var b=c.f*c.g*c.scale,g=c.b*c.g*c.scale,l=c.a*c.g*c.scale,q=c.color,v=c.c,G=c.x-g/2;c=c.y-l/2;var p=l;v=v?v:"";D.strokeStyle=
q;D.fillStyle=q;D.lineJoin="round";D.lineWidth=b;v&&D.strokeRect(G+.5*b,c+.5*b,g-b,l-b);"top"===v?(c+=.5*b,p-=.5*b):"bottom"===v?p-=b:"both"===v&&(c+=.5*b,p-=b);D.fillRect(G,c,g,p);D.stroke();D.fill()}};var O=null,R=null,U={bottomBun:{b:50,a:8,c:"bottom",color:"#d2aa99",f:5},burger:{b:48,a:8,c:"both",color:"#854c30",f:7},lettuce:{b:48,a:3,c:"both",color:"#6daa2c",f:2},tomato:{b:45,a:3,color:"#d04648",f:2},cheese:{b:45,a:2,c:"both",color:"#dad45e",f:2},onion:{b:45,a:2,c:"both",color:"#8595a1",f:2},topBun:{b:50,a:10,c:"top",color:"#d2aa99",f:10}};function ea(){if(!R){R=[];for(var c in U)-1===c.indexOf("Bun")&&R.push(c)}return R}var fa=["Excellent","Fantastic","Good Job","Awesome","Sick Move"];var J=null,D=null;
(function(){function c(){J=document.createElement("canvas");D=J.getContext("2d");document.body.insertBefore(J,document.body.childNodes[0]);window.addEventListener("resize",function(){V()});window.addEventListener("click",function(a){K=a.pageX;P=a.pageY});window.addEventListener("touchstart",function(a){K=a.pageX;P=a.pageY});V();v();r()}function b(a){m.muteSound||t.play(a)}function g(a){m.muteMusic||t.o(a)}function l(){m.muteSound=!m.muteSound;E.toggleMuteSound.text="Sound "+(m.muteSound?"Off":"On");
S()}function q(){m.muteMusic=!m.muteMusic;m.muteMusic?t.u():t.s();E.toggleMuteMusic.text="Music "+(m.muteMusic?"Off":"On");S()}function v(){E={start:new C("Start",{x:"center",y:30,b:22,a:12,position:"bottom",font:"Tahoma",fontSize:8,color:"#30346d",mode:w.i,onclick:W}),toggleMuteSound:new C("Sound "+(m.muteSound?"Off":"On"),{x:30,y:33,b:20,a:6,position:"bottom-center",font:"Tahoma",fontSize:4,color:"#4e4a4e",mode:w.i,onclick:l}),toggleMuteMusic:new C("Music "+(m.muteMusic?"Off":"On"),{x:30,y:26,b:20,
a:6,position:"bottom-center",font:"Tahoma",fontSize:4,color:"#4e4a4e",mode:w.i,onclick:q}),playAgain:new C("Play Again",{x:"center",y:15,b:40,a:12,position:"bottom",font:"Tahoma",fontSize:8,color:"#30346d",mode:w.j,onclick:W}),endBack:new C("Back",{x:-36,y:15,b:22,a:12,position:"bottom-center",font:"Tahoma",fontSize:8,color:"#4e4a4e",mode:w.j,onclick:r}),clear:new C("Clear",{x:-36,y:30,b:22,a:12,position:"bottom-center",font:"Tahoma",fontSize:8,color:"#30346d",mode:w.h,onclick:function(){X();b("clear")}}),
back:new C("Back",{x:-36,y:10,b:22,a:12,position:"center",font:"Tahoma",fontSize:8,color:"#4e4a4e",mode:w.h,onclick:r}),submit:new C("Go",{x:0,y:30,b:22,a:12,position:"bottom-center",font:"Tahoma",fontSize:8,color:"#30346d",mode:w.h,onclick:ha})};var a="bottomBun burger cheese tomato onion lettuce topBun".split(" "),e=-36,d,n=a.length;for(d=0;d<n;d++)G(a[d],e,12),e+=12}function G(a,e,d){var n=p(a),h="both";-1<a.indexOf("top")?h="top":-1<a.indexOf("bottom")&&(h="bottom");E[a]=new C("",{x:e,y:d,b:10,
a:10,position:"bottom-center",font:"Tahoma",fontSize:8,c:h,color:n.color,mode:w.h,onclick:function(){b("addPart");m.currGame.currRound.burgerArr.push(a)}})}function p(a){var e=U[a];e||console.log("Part '"+a+"' was not found!");return e}function r(){E.start.hidden=!1;H=w.i;g("menuBgMusic")}function W(){m.currGame={roundCount:3,level:1,startTime:(new Date).getTime(),time:0,currRound:Y(Math.floor(4*Math.random())+2),rounds:[]};T("START","#346524");H=w.h;g("gameBgMusic")}function Y(a){var e=["bottomBun"],
d;for(d=0;d<a;d++)e.push(z(ea()));e.push("topBun");return{targetBurgerArr:e,burgerArr:[]}}function ia(){if(K){var a=K,e=P;for(A in E){var d=E[A];if(d.mode===H){var n="center"===d.x?x:d.x*k;var h=d.y*k;-1<d.position.indexOf("center")&&(n=x+n);-1<d.position.indexOf("bottom")&&(h=F-h);var u=n-d.b/2*k;var B=h-d.a/2*k;n+=d.b/2*k;h+=d.a/2*k;if(a>u&&a<n&&e>B&&e<h){d.onclick();break}}}P=K=!1}N.clear("#140c1c");switch(H){case w.i:a=10*k;e=x;d=L-20*k;if(!O){O=[];for(var f in U)O.push(f)}Q(O,e,d,.7);d+=20*k;
N.text("Burger Builder",{x:e,y:d,fontSize:a,align:"center",color:"#757161"});d=F-6*k;a=2*k;N.text("Background music from PlayOnLoop.com",{x:e,y:d,fontSize:a,position:"bottom-center",color:"#757161"});d+=3*k;N.text("Licensed under Creative Commons by Attribution 4.0 (https://creativecommons.org/licenses/by/4.0/)",{x:e,y:d,fontSize:a,position:"bottom-center",color:"#757161"});break;case w.h:f=m.currGame.currRound.targetBurgerArr;Q(f,x,22*k,.55);Z(f,x+22*k,19.8*k,.55);f=m.currGame.currRound.burgerArr;
Q(f,x,L,1);Z(f,x+40*k,L,1);break;case w.j:d=10*k;f=x;a=15*k;e=m.currGame;u=Math.round(e.time/1E3*100)/100+"s";N.text("Complete",{x:f,y:a,fontSize:d,align:"center",color:"#757161"});a+=.8*d;N.text("Time: "+u+", Level: "+e.level+", Rounds: "+e.rounds.length,{x:f,y:a,fontSize:.5*d,align:"center",color:"#757161"});B=0;var A=30*k;n=20*k;h=e.rounds.length;a+=A/2;f=x-A;for(d=0;d<h;d++)u=e.rounds[d].burgerArr,Q(u,f,a,.3),3===++B?(B=0,f=x-A,a+=n):f+=A}I&&(f=(new Date).getTime()-I.time,2E3>f?(a=0,0<f-1E3&&
(a=1-(f-1E3)/1E3),N.text(I.text,{x:x,y:L,fontSize:10*k,align:"center",color:I.color,opacity:0>a?1:a})):I=!1);for(var y in E)f=E[y],f.mode===H&&(a="center"===f.x?x:f.x*k,e=f.y*k,-1<f.position.indexOf("center")&&(a=x+a),-1<f.position.indexOf("bottom")&&(e=F-e),d=f.fontSize*k,N.l({x:a,y:e,b:f.b,a:f.a,f:3,color:f.color,g:k,c:f.c,scale:1}),f.text&&N.text(f.text,{x:a,y:e+.3*d,b:f.b,a:f.a,fontSize:d,fontStyle:f.font,align:"center",color:"#6dc2ca"}))}function Z(a,e,d,n){var h=a.length;d-=8*k*h*n/2;for(--h;0<=
h;h--){var u=a[h];if(-1===u.indexOf("Bun")){u=p(u);if(!u)break;0<h&&(d+=8*n*k);N.l({x:e,y:d,b:8,a:8,f:1,color:u.color,g:k,c:"both",scale:n})}}}function Q(a,e,d,n){var h=n;h||(h=1);var u,B=0,f=a.length;for(u=0;u<f;u++){var A=a[u];A=p(A);B+=A.a*h*k}d-=B/2;B=a.length;for(h=B-1;0<=h;h--){u=y;var y=a[h];y=p(y);h<B-1&&(d=u?d+(y.a*n/2+u.a*n/2)*k:d+y.a*n/2*k);N.l({x:e,y:d,b:y.b,a:y.a,f:y.f,color:y.color,g:k,c:y.c,scale:n})}}function X(){m.currGame.currRound.burgerArr=[]}function ha(){console.log("Submit");
var a=m.currGame.currRound.burgerArr,e=m.currGame.currRound.targetBurgerArr,d=a.length,n=!0;d!==e.length&&(n=!1);if(n){var h;for(h=0;h<d;h++)if(a[h]!==e[h]){n=!1;break}}n?(m.currGame.rounds.push(m.currGame.currRound),T(z(fa)+"!","#346524"),b("match"),a=m.currGame,a.rounds.length<a.roundCount?a.currRound=Y(Math.floor(4*Math.random())+2):(console.log("GAME IS DONE"),H=w.j,g("menuBgMusic"),a=m.currGame,a.time=(new Date).getTime()-a.startTime,m.history.push(a),S())):(T("NO MATCH","#d04648"),b("noMatch"),
X())}function T(a,e){I={text:a,color:e,time:(new Date).getTime()}}function ja(a){var e=window.localStorage.getItem("burger-builder");e&&((e=JSON.parse(e))?m=e:console.error("ERROR: loading local storage data."));a()}function V(){M=window.innerWidth;J.width=M;x=M/2;F=window.innerHeight;J.height=F;L=F/2;k=M<F?M/110:F/110}function S(){window.localStorage.setItem("burger-builder",JSON.stringify(m))}var w={i:1,h:2,j:3},E={},H=w.i,k,M,F,x,L,K,P,I=!1,m={currGame:{roundCount:5,time:0,level:1,currRound:{targetBurgerArr:[],
burgerArr:[]},rounds:[]},muteSound:!1,muteMusic:!1,history:[]};window.onload=function(){ja(function(){t.m(function(){c();setInterval(ia,10)})})};return{v:D}})();
