var ea="function"==typeof Object.defineProperties?Object.defineProperty:function(c,b,h){c!=Array.prototype&&c!=Object.prototype&&(c[b]=h.value)};function fa(c){c=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,c];for(var b=0;b<c.length;++b){var h=c[b];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");}var ha=fa(this);
function ia(c,b){if(b){var h=ha;c=c.split(".");for(var n=0;n<c.length-1;n++){var q=c[n];q in h||(h[q]={});h=h[q]}c=c[c.length-1];n=h[c];b=b(n);b!=n&&null!=b&&ea(h,c,{configurable:!0,writable:!0,value:b})}}ia("Array.prototype.fill",function(c){return c?c:function(b,h,n){var q=this.length||0;0>h&&(h=Math.max(0,q+h));if(null==n||n>q)n=q;n=Number(n);0>n&&(n=Math.max(0,q+n));for(h=Number(h||0);h<n;h++)this[h]=b;return this}});
var p=null,u=null,y=null,z={addPart:"addPart - Jump 1.wav",clear:"clear - Select 1.wav",endGame:"endGame - Victory SoundFX2.ogg",match:"match - Fruit collect 1.wav",noMatch:"noMatch - Text 1.wav",gameBgMusic:"game - POL-star-way-short.wav",menuBgMusic:"menu - POL-follow-me-short.wav"};function ja(c){if(!y){y={};for(var b in z)y[b]=new Audio("./audio/"+z[b])}c()}function G(c){H(u);var b=M(c);b&&(b.play(),b.loop=!0,b.volume=.1);u=c}
function M(c){var b=y[c];return b?b:(console.log("Sound '"+c+"' not found"),null)}function H(c){if(c){var b=y[c];b?b.pause():console.log("Sound '"+c+"' not found")}};function P(c){return c[Math.floor(Math.random()*c.length)]};function T(c,b){this.text=c;this.x=b.x;this.y=b.y;this.b=b.b;this.a=b.a;this.font=b.font;this.fontSize=b.fontSize;this.color=b.color;this.mode=b.mode;this.hidden=!1;this.c=b.c||"both";this.g=b.g;this.position=b.position;this.onclick=b.onclick};var W={text:function(c,b){var h=b.align||"center",n=b.opacity||1,q=b.x,w=b.y;U.font=b.fontSize+"px "+(b.fontStyle||"Arial");U.fillStyle=b.color;U.globalAlpha=n;b=U.measureText(c);"center"===h?q-=b.width/2:"right"===h&&(q-=b.width);U.fillText(c,q,w);U.globalAlpha=1},clear:function(c){U.fillStyle=c||"white";U.clearRect(0,0,V.width,V.height);U.fillRect(0,0,V.width,V.height)},l:function(c){var b=c.f*c.g*c.scale,h=c.b*c.g*c.scale,n=c.a*c.g*c.scale,q=c.color,w=c.c,L=c.x-h/2;c=c.y-n/2;var A=n;w=w?w:"";U.strokeStyle=
q;U.fillStyle=q;U.lineJoin="round";U.lineWidth=b;w&&U.strokeRect(L+.5*b,c+.5*b,h-b,n-b);"top"===w?(c+=.5*b,A-=.5*b):"bottom"===w?A-=b:"both"===w&&(c+=.5*b,A-=b);U.fillRect(L,c,h,A);U.stroke();U.fill()}};var X=null,Y={bottomBun:{b:50,a:8,c:"bottom",color:"#d2aa99",f:5},burger:{b:48,a:8,c:"both",color:"#854c30",f:7},lettuce:{b:48,a:3,c:"both",color:"#6daa2c",f:2},tomato:{b:45,a:3,color:"#d04648",f:2},cheese:{b:45,a:2,c:"both",color:"#dad45e",f:2},onion:{b:45,a:2,c:"both",color:"#8595a1",f:2},topBun:{b:50,a:10,c:"top",color:"#d2aa99",f:10}};function ka(){if(!X){X=[];for(var c in Y)-1===c.indexOf("Bun")&&X.push(c)}return X}var la=["Excellent","Fantastic","Good Job","Awesome","Sick Move"];var V=null,U=null;
(function(){function c(){V=document.createElement("canvas");U=V.getContext("2d");document.body.insertBefore(V,document.body.childNodes[0]);Z();window.addEventListener("resize",function(){Z()});window.addEventListener("click",function(a){I=a.pageX;N=a.pageY});window.addEventListener("touchstart",function(a){I=a.pageX;N=a.pageY});w();Q()}function b(a){if(!m.muteSound){H(p);var d=M(a);d&&d.play();p=a}}function h(a){m.muteMusic||G(a)}function n(){m.muteSound=!m.muteSound;B.toggleMuteSound.text="Sound "+
(m.muteSound?"Off":"On")}function q(){m.muteMusic=!m.muteMusic;m.muteMusic?H(u):(console.log("Sound.lastMusicName="+u),G(u));B.toggleMuteMusic.text="Music "+(m.muteMusic?"Off":"On")}function w(){B={start:new T("Start",{x:"center",y:30,b:22,a:12,position:"bottom",font:"Arial",fontSize:8,color:"#30346d",mode:r.i,onclick:aa}),toggleMuteSound:new T("Sound "+(m.muteSound?"Off":"On"),{x:30,y:33,b:20,a:6,position:"bottom-center",font:"Arial",fontSize:4,color:"#4e4a4e",mode:r.i,onclick:n}),toggleMuteMusic:new T("Music "+
(m.muteMusic?"Off":"On"),{x:30,y:26,b:20,a:6,position:"bottom-center",font:"Arial",fontSize:4,color:"#4e4a4e",mode:r.i,onclick:q}),playAgain:new T("Play Again",{x:"center",y:15,b:40,a:12,position:"bottom",font:"Arial",fontSize:8,color:"#30346d",mode:r.j,onclick:aa}),endBack:new T("Back",{x:-36,y:15,b:22,a:12,position:"bottom-center",font:"Arial",fontSize:8,color:"#4e4a4e",mode:r.j,onclick:Q}),clear:new T("Clear",{x:-36,y:30,b:22,a:12,position:"bottom-center",font:"Arial",fontSize:8,color:"#30346d",
mode:r.h,onclick:function(){ba();b("clear")}}),back:new T("Back",{x:-36,y:10,b:22,a:12,position:"center",font:"Arial",fontSize:8,color:"#4e4a4e",mode:r.h,onclick:Q}),submit:new T("Go",{x:0,y:30,b:22,a:12,position:"bottom-center",font:"Arial",fontSize:8,color:"#30346d",mode:r.h,onclick:ma})};var a="bottomBun burger cheese tomato onion lettuce topBun".split(" "),d=-36,e,k=a.length;for(e=0;e<k;e++)L(a[e],d,12),d+=12}function L(a,d,e){var k=A(a),g="both";-1<a.indexOf("top")?g="top":-1<a.indexOf("bottom")&&
(g="bottom");B[a]=new T("",{x:d,y:e,b:10,a:10,position:"bottom-center",font:"Arial",fontSize:8,c:g,color:k.color,mode:r.h,onclick:function(){b("addPart");m.currGame.currRound.burgerArr.push(a)}})}function A(a){var d=Y[a];d||console.log("Part '"+a+"' was not found!");return d}function Q(){B.start.hidden=!1;C=r.i;h("menuBgMusic")}function aa(){m.currGame={rounds:3,level:1,startTime:(new Date).getTime(),time:0,currRound:ca(),history:[]};R("START","#346524");C=r.h;h("gameBgMusic")}function ca(){var a=
["bottomBun"],d=Math.floor(4*Math.random())+2,e;for(e=0;e<d;e++)a.push(P(ka()));a.push("topBun");return{targetBurgerArr:a,burgerArr:[]}}function na(){if(I){var a=I,d=N;for(D in B){var e=B[D];if(e.mode===C){var k="center"===e.x?t:e.x*f;var g=e.y*f;-1<e.position.indexOf("center")&&(k=t+k);-1<e.position.indexOf("bottom")&&(g=E-g);var l=k-e.b/2*f;var x=g-e.a/2*f;k+=e.b/2*f;g+=e.a/2*f;if(a>l&&a<k&&d>x&&d<g){e.onclick();break}}}N=I=!1}W.clear("#140c1c");switch(C){case r.i:a=10*f;d=t;e=J-15*f;W.text("\ud83c\udf54",
{x:d,y:e,fontSize:20*f,align:"center",color:"#757161"});W.text("Burger Builder",{x:d,y:e+1.2*a,fontSize:a,align:"center",color:"#757161"});e=E-6*f;a=2*f;W.text("Background music from PlayOnLoop.com",{x:d,y:e,fontSize:a,position:"bottom-center",color:"#757161"});e+=3*f;W.text("Licensed under Creative Commons by Attribution 4.0 (https://creativecommons.org/licenses/by/4.0/)",{x:d,y:e,fontSize:a,position:"bottom-center",color:"#757161"});break;case r.h:a=m.currGame.currRound.targetBurgerArr;S(a,t,22*
f,.55);da(a,t+22*f,19.8*f,.55);a=m.currGame.currRound.burgerArr;S(a,t,J,1);da(a,t+40*f,J,1);break;case r.j:l=10*f;a=t;d=15*f;e=m.currGame;x=Math.round(e.time/1E3*100)/100+"s";W.text("Complete",{x:a,y:d,fontSize:l,align:"center",color:"#757161"});d+=.8*l;W.text("Time: "+x+", Level: "+e.level+", Rounds: "+e.rounds,{x:a,y:d,fontSize:.5*l,align:"center",color:"#757161"});var D=0;k=30*f;g=20*f;var K=e.history.length;d+=k/2;a=t-k;for(l=0;l<K;l++)x=e.history[l],S(x,a,d,.3),3===++D?(D=0,a=t-k,d+=g):a+=k}F&&
(a=(new Date).getTime()-F.time,2E3>a?(d=0,0<a-1E3&&(d=1-(a-1E3)/1E3),W.text(F.text,{x:t,y:J,fontSize:10*f,align:"center",color:F.color,opacity:0>d?1:d})):F=!1);for(var v in B)a=B[v],a.mode===C&&(d="center"===a.x?t:a.x*f,e=a.y*f,-1<a.position.indexOf("center")&&(d=t+d),-1<a.position.indexOf("bottom")&&(e=E-e),l=a.fontSize*f,W.l({x:d,y:e,b:a.b,a:a.a,f:3,color:a.color,g:f,c:a.c,scale:1}),a.text&&W.text(a.text,{x:d,y:e+.3*l,b:a.b,a:a.a,fontSize:l,align:"center",color:"#6dc2ca"}))}function da(a,d,e,k){var g=
a.length;e-=8*f*g*k/2;for(--g;0<=g;g--){var l=a[g];if(-1===l.indexOf("Bun")){l=A(l);if(!l)break;0<g&&(e+=8*k*f);W.l({x:d,y:e,b:8,a:8,f:1,color:l.color,g:f,c:"both",scale:k})}}}function S(a,d,e,k){var g=k;g||(g=1);var l,x=0,D=a.length;for(l=0;l<D;l++){var K=a[l];K=A(K);x+=K.a*g*f}e-=x/2;x=a.length;for(g=x-1;0<=g;g--){l=v;var v=a[g];v=A(v);g<x-1&&(e=l?e+(v.a*k/2+l.a*k/2)*f:e+v.a*k/2*f);W.l({x:d,y:e,b:v.b,a:v.a,f:v.f,color:v.color,g:f,c:v.c,scale:k})}}function ba(){m.currGame.currRound.burgerArr=[]}
function ma(){console.log("Submit");var a=m.currGame.currRound.burgerArr,d=m.currGame.currRound.targetBurgerArr,e=a.length,k=!0;e!==d.length&&(k=!1);if(k){var g;for(g=0;g<e;g++)if(a[g]!==d[g]){k=!1;break}}k?(m.currGame.history.push(a),R(P(la)+"!","#346524"),b("match"),a=m.currGame,d=a.history.length,console.log("roundsSoFar="+d),d<a.rounds?a.currRound=ca():(console.log("GAME IS DONE"),C=r.j,h("menuBgMusic"),a=m.currGame,a.time=(new Date).getTime()-a.startTime,m.history.push(a),window.localStorage.setItem("burger-builder",
JSON.stringify(m)))):(R("NO MATCH","#d04648"),b("noMatch"),ba())}function R(a,d){F={text:a,color:d,time:(new Date).getTime()}}function oa(a){var d=window.localStorage.getItem("burger-builder");d&&((d=JSON.parse(d))?m=d:console.error("ERROR: loading local storage data."));a()}function Z(){O=window.innerWidth;V.width=O;t=O/2;E=window.innerHeight;V.height=E;J=E/2;f=O/100;6.25<f&&(f=6.25)}var r={i:1,h:2,j:3},B={},C=r.i,f,O,E,t,J,I,N,F=!1,m={currGame:{rounds:5,time:0,level:1,currRound:{targetBurgerArr:"bottomBun tomato cheese onion burger lettuce topBun".split(" "),
burgerArr:"bottomBun tomato cheese onion burger lettuce topBun".split(" ")},history:[]},muteSound:!1,muteMusic:!1,history:[]};window.onload=function(){oa(function(){ja(function(){c();setInterval(na,50)})})};return{m:U}})();
